---
title: "오픈 마인드 진보에게 보내는 공개서한(1)"
author: 'MENCIUS MOLDBUG'
date: '2020-12-16'
slug: 오픈-마인드-진보에게-보내는-공개서한
categories: []
tags:
  - NRx
  - 반동주의
---
미완성 번역

# 1장: 캔버스로 만든 수평선

당신은 오픈마인드를 가진 진보주의자인가? 본인 스스로 그런쪽이 아닐 수도 있겠지만 적어도 당신의 친구들중에선 그런 오픈마인드를 가진 사람이 있을 것이다. 이 글은 당신이나 혹은 그들이나 오픈마인드를 가진 진보들을 위한 글이다.  아마 이글은  나의 블로그, [Unqualified Reservations](https://www.unqualified-reservations.org/)를 소개하는 일종의 입문서 역할이라 보면 되겠다.

만약 당신이 오픈마인드 진보주의자라면 아마 가톨릭 신자는 아닐 것이다 (또한 당신은교황이라는 개념을 진지하게 생각하지도 않을 것이다). 가톨릭 신자들한테 공개 편지를 써서, 로마의 음흉한 지배로부터 그들의 생각을 해방시킬 수 있게 설득하는 것을 상상해보자. 이런 방식은 구식이기도 하겠지만, 그무엇보다도, 어떻게 시작하겠냐는게 관건이겠다. 하지만 이곳 UR(Unqualified Reservation)에서는 구식이 되는 것을 결코 두려워하지 않는다. 그리고 그 시작에 관해서는, 우리는 이미 알고 있다.

진보주의자가 되는 것은 가톨릭 신자가 되는 것과 같을까? 안될게 뭐가 있나?  가톨릭과 진보주의 둘다 일련의 믿음을 통해 세상을 이해하는 방식 이다. 이 믿음들은 사실일 수도 있고, 거짓일 수도 있고, 거짓일 만큼 충분히 이치에 맞지 않는 [헛소리](https://www.unqualified-reservations.org/archive/stove/)일 수도 있다. 오픈마인드 진보주의자(혹은 오픈마인드 가톨릭 신자)로서, 당신은 당신이 가지고 있는 모든 신념이 진실이라고 생각하겠지만 , 아마 약간의 온화한 도움이 함께라면 그 신념들을 다시 생각해볼 용의도 있을 것이다.

가톨릭과 진보주의 사이에는 다음과 같은 큰 차이가 있다. 천주교는 이른바 '종교'다. 종교의 핵심 신념은 정신 세계에 대한 주장인데, 이 주장은 가톨릭 신자(물론 교황을 제외하고)들 스스로 경험한 바가 없다. 반면에 진보적인 믿음은 현실 세계, 즉 정부, 역사, 경제, 사회에 대한 주장인 경향이 있다. 이러한 것들은, 성 삼위일체와는 달리, 우리 모두가 직접 경험하는 현상들이다.

그런데 그게 과연 진실일까? 우리 대부분은 정부를 위해 일한 적도 없고, 정부가 하는 일의 아주 작은 부분만 봐온 사람들이다. 역사는 책에서 나온 것이다. 이  책에서 나온 역사라는게 성경은 아니다, 아니면 그게  맞을지 도? 우리의 경제학에 대한 개인적인 경험은 무엇인가? 휘발유 가격인가? 그외 기타  등등... 당신의 삶이 길고 상당히 특이한게 아니라면, 나는 당신이 정부, 역사 등에 대한 위대한 의문들에 대해 깊히 고려해보지 않았을거라  본다. 내 사상을 보면 확실히 그렇지 않으니까.

물론 흔히들 진보사상의 상당 부분은 순수이성의 산물이라고 일컬어지고 있다. 그런가? 토마스 아퀴나스는 순수이성으로부터 가톨릭을 파생시켰다. 존 롤스는 순수 이성으로부터 진보주의를 이끌어냈다. 적어도 그들 중 한 명은 실수를 했을 것이다. 아니면 둘 다 그랬을 수도 있다. 그들의 저작들을 직접 확인해보았는가? 한 가지 나쁜 변수가 당신의 모든 증거를 무너뜨릴 것이다.

그리고 정말 그게 맞는 말일까? 당신이 진보인 이유가 아무것도 믿지 않는 데서 출발했으며("우리는 [허무주의자](https://www.youtube.com/watch?v=Y5J_kao6mwA)다! 우리는 아무것도 믿지 않는다!") 그걸 바탕으로 생각해온게 진보이기때문이라 생각하는가? 물론 나는 당신의 경험을 대변할 수는 없지만, 당신의 부모가 진보주의자였기 때문에 진보주의자이거나, 아니면 어떤 책이나 선생을 통해서라던지 혹은 다른 지적인 경험에 의해 진보로 전향되었을 것이라 본다. 이런 방식은 바로 가톨릭 신자가 되는 것과 똑같을 수밖에 없다 .

하지만 거기엔 한가지 차이점이 있긴 있다. 가톨릭 신자가 되려면 믿음을 가져야 한다, 왜냐하면 아무도 성령을 직접 본 적이 없으니까. 진보주의자가 되기 위해서는 신뢰가 있어야 한다, 왜냐하면 자신의 세계관이 실제 세계를 정확하게 반영한다 믿고있으니까- 당신 혼자만의 작은 눈으로 보는 경험이 아니라, 인류 전체의 경험으로서.

하지만 당신은 '인류 전체의 경험'이란걸 공유해보지 못했다. 당신은 단지 그것으로부터 편집된 글들, 녹음물, 비디오의 말뭉치를 읽고 듣고 보았을 뿐이다. 그리고 이런 것들이 도대체 누구에 의해 편찬되었는가? 거기에서부터 신뢰가 나오는건데 이에대한 설명이 좀 더 필요하다.

나는 진보주의자는 아니지만, 과거에 진보주의자로 자랐다. 나는 샌프란시스코에 살고 있고, 외교관 부모가정에서 자랐으며, 브라운 대학에 진학했으며, 80년대 중반부터 [Tom's of Maine](https://en.wikipedia.org/wiki/Tom%27s_of_Maine)으로 이를 닦았다. 내게 일어난 일이란, 난 신뢰를 잃어버렸다는 것이다.

[데이비드 마멧](https://en.wikipedia.org/wiki/David_Mamet)도 신뢰를 잃었다. 그가 빌리지 보이스지에 쓴 [에세이](http://www.villagevoice.com/news/david-mamet-why-i-am-no-longer-a-brain-dead-liberal-6429407)는 읽어볼만 하다, 세계에서 가장 유명한 극작가가 더 이상 자신이 '뇌절한 리버럴'이 아니라고 선언하는 '충격적인' 사실만 볼때에는 말이다. 그 기사에 달린 댓글은 500여 개다. 내가 놓쳤을지도 모르는 부분이지만 마멧이 깨달음을 얻었다거나 하는 긍정적인 댓글은 보이지 않는다.

물론 마멧은 전형적인 마멧이다. 그는 충격에 빠진 것이지 전향한 것이 아니다.  리버럴이라는 단어조차도, 적어도 오늘날 정치적 이해관계 속에서는 , 모욕적인 언사로 통용된다. 그것은 마치 가톨릭 출신이었던 전향자가 "왜 나는 더 이상 뇌절한 천주교빠가 아닌가"라고 설명하는 것과 같다. 존 스튜어트 밀은 리버럴이었다. 버락 오바마는 진보주의자이고, 당신 또한 진보주의자이다. 예의의 기본 원칙: 사람들이 스스로 부르지 않는 이름을 부르지 말라.

더욱이 마멧은 진보주의만 배척하는 것이 아니다. 그는 보수주의를 지지한다. 하느님 맙소사! 좀더 어려운 문제에 접근해보자. 당신은 모든 사람이 가톨릭 신자 혹은 힌두교 신자로 되어있는 나라에 살고 있다 가정해보자. 이미 사람들을 로마인들의 악랄한 손아귀(가톨릭)으로부터 때어내는 것 만으로도 힘들지 않은가? 그렇다면 반대로 사람들을 칼리, 크리슈나, 가네샤 신들을 숭배하게 하는게 맞는걸까?

예를 들어, 마멧은 보수주의 작가 [토마스 소웰](https://en.wikipedia.org/wiki/Thomas_Sowell)을 지지하는데, 그에 의하면 "우리 현대 최고의 철학자"라며 소웰을 칭송하고 있다. 글쎄 나도 토마스 소웰을 좋아하긴 한다. 그의 작품은 확실히 가치가 없는 것은 아니다. 그리고 구글에 검색하면 그의 칼럼이 [townhall.com](http://townhall.com/)이라는 보수주의적인 웹사이트에 자주 뜨는 것을 볼 수 있을 것이다.

위 예시의 링크를 클릭해보면 *극악한* 그래픽 디자인을 볼 수 있을 것이다. (오바마 캠페인 그래픽 디자인과 비교해놓고 봤을때 오바마쪽이 얼마나 앞선 디자인인지 차이가 느껴지시는가? 일부 폰트 디자이너들에 따르면 바로 [차이](https://archive.is/KSPs8)가 느껴진다고 한다.) 거기에서 폭스뉴스를 연상시키는 참혹함을 체험해보자. 그다음엔... 뭐, "뒤로가기"를 누르던지 아니면 덤으로 앤 콜터 칼럼을 읽거나, 아님말고. 

난 진보주의자가 아니지만 그렇다고 보수주의자도 아니다. (궂이 따지자면 난 [자코바이트](https://en.wikipedia.org/wiki/Jacobitism)다.) 오랜시간을 통해 나는 미국 보수주의 사상이 어떻게 돌아가는지 알게되었다. 일반적으로 폭스뉴스나 townhall.com에서 잘 팔리는 얘기들이 바로 그런 것이다. 일종의 호불호가 갈리는 맛이랄까? 이건 아마 버락 오바마가 제레미아 라이트 목사의 설교 스캔들을 다루는 방식과 매우 비슷하다고 볼 수 있다.  데이비드 마멧이 독자들에게 townhall.com을 설명하기 위한 방식은, 마치 살짝 동성애자에 꺼림직한 삼촌을, 게이는 딱히 나쁘지 않다는 설득을 위해 [살로소돔의 120일](https://www.imdb.com/title/tt0073650/)을 틀어주는 것과 같은 짓이다. 이건 소통이라기보단 "엿먹어라"에 가까운 짓이다.    

그런데 많은 이들은 자신이 진보가 될 수 없다면 보수주의자가 될 수 밖에 없다고 생각한다. 내가 예측하기로는, 많은 부류의 진보들이 갖는 감정적 동기로서 그들이 진보인 이유는 보수주의는 답이없고, 보수주의에 대해 근본적으로 무언가 뜯어 고쳐져야된다 생각되기 때문일 것이다. 게임오버, 또다시 제자리로.

NPR은 틀렸고 폭스뉴스가 옳다는 생각은 어디서 나온 것일까? NPR과 폭스뉴스는 서로 모순되는 말을 하기때문에 둘 다 옳을 수는 없는 노릇이다. 하지만 혹시 둘다 틀린 것은 아닐까? 나는 거기에서 나오는 정보들이 약간  틀렸다거나, 각각 반은 옳고 반은 틀렸다는 걸 말하려는 것도 아니며, 진실은 그들 사이에 있다는 것을 말하는 것도 아니다. 내가 말하고자 하는 바는  그것들 둘 다 현실과는 일관되지 않은 내용들을 담고 있다는 것이다.

이 점에 대해서는 잠시 생각해 보자. 진보주의자로서, 당신은 보수가 집단적 망상이라고 믿을 수 밖에 없다. 얼마나 기상천외한 일인가! 수많은 사람들중 에 대부분 둔하지만 꽤 똑똑한 사람들 조차도 그러한 망상속에서 살아간다. 우리는 이것을 당연하게 여긴다. 또한 우리는 이런 세태에 익숙해져있다. 하지만 곰곰히 생각해보면 이건 정말 이상한 일로 느껴질 수밖에 없다.

우리가 믿어야 할 것은 보수들은 그들 집단적으로 정보를 잘못 받아들여 오해를 하고 있다는 것이다. 그들은 바보가 아니다. 적어도 그들 모두가 바보는 아니다. 또한 그들이 악한 것도 아니다. townhall.com에서 시간을 보내다 보면 골룸 같은 놈들이 세계를 파괴시키고 노예화하려는 사악한 계획 따위는 찾아볼 수 없을 것이다.그들은 당신과 같이, 보수주의자가 됨으로서 선과 진실을 위해 싸우고 있다고 생각하고 있는 것이다.   


보수주의는 정부에 대한 개인적 경험이 없는 다수의 사람들이 갖고 있는 정부론이다. 그들은 주로 폭스 뉴스, townhall.com,  지역교회에서 나오는 선택적인 정보들을 통해 그들만의 정리된 이야기를 지지하고, 강화시키고, 확증에 들게한다.


그렇다면 왜 이런 이상한 패턴들이 존재하는 것일까? 왜냐하면 보수주의라 함은 일반적인 의견이 아니기때문이다. 정부론에 대한 논의 대신 보수를 농구와의 비유로 생각해보자. "보수주의"는 농구 선수와 코치들에게 중요한 픽앤롤 전법, 외곽운용, 삼각수비 그리고 다른 이슈들에 대한 관점의 체계일 것이다.

분명한 차이점은, 당신이 농구 코치가 아니라면, 농구 문제에 대한 당신의 의견은 전혀 반영되지 않을 것이다. 농구는 민주주의가 아니기 때문이다. 선수들은 팬들은 고사하고 투표조차 받지않는다. 그러나 보수주의는 일종의 '조직적인 망상'을 유지할 수 있는데, 왜냐하면 보수주의의 팬들은 단순한 팬이 아니기 때문이다: 그들은 정치 기계의 지지자들이다. 이 기계는 자신의 지지자들을 지키지 못하면 없어질 것이므로 지지자들을 지킬 동기가 생긴다. 그리고 그것은 정말로 그렇게 작동한다. 그게 어떻게 작동하는지도 보면 웃길따름이다.

자, 진보주의자로서 당신이 보는 미국의 민주주의는 이렇다-진실과 이성이 프로파간다, 무지, 거짓정보 위에 세워진 준범죄적 정치 기계와 대결하는 경합이다. 아마 세상을 냉소적으로 보는 시각일 텐데 진보주의가 옳다고 믿는다면 보수가 잘못됐다고 믿을 수밖에 없고, 다른 선택의 여지가 없을 것이다.

그러나 여기 더 비관적인 견해가 있다. 미국의 민주주의가 진리와 이성의 경합이 아니라 두 개의 준범죄적 정치 기계 사이의 경합이라고 가정해 보자. 진보주의도 보수주의와 똑같다고 볼 수 있을까? 만약 그렇다면, 누가 당신에게 그런 점을 알려주겠는가?

보수주의를 일종의 정신질환으로 생각해보자. 모기가 말라리아를 옮기는 수준의 전염성을 가진 폭스뉴스를 통한 바이러스 X가 미국인구 절반의 뇌를 잠식시켜 조지부시는 사실 '정상인'이고 지구온난화는 일어나지 않으며, 미군이야말로 사드르 시티에 진정한 민주주의를 가져올 수 있다고 믿게 만들었다. 다행이도 나머지 미국의 절반인구는 진보적인 항체로 보호되고 있는데, 이 항체는 매일 타임즈와 NPR이 제공하는 젖과 꿀물을 마시며 진실의 빛을 비출 수 있게 해준다.

그런데 그게 실제로 그런가? 방금 우리는 두 종류의 실체를 가정해 보았다. 바이러스와 항체, 모기, 그리고 젖과 꿀물. [오컴의 윌리엄](https://en.wikipedia.org/wiki/Occam%27s_Razor)은 방금의 가정에 행복해하지 않을 것이다. 대신에 우리가 바이러스 Y를 다루고 있다고 상상하는 것이 더 간단하지 않은가? 한 세트의 사람들이 감염되고 다른 한 세트는 면역이되는 것이 아니라, 모든 사람들이 감염된다. 단지 다른 변종들로 이루어지는 것일 뿐이다.

바이러스 X를 바이러스로 만드는 것은, 영화 죠스에 나오는 상어처럼, 이것들의 인생 유일한 목표는 먹고, 헤엄치고, 아기 바이러스를 만드는 것뿐이다. 즉, 그 특징은 여러상황에 따라 설명될 수 있다. 이게 만일 정확한 대변을 통해 실현 될 수 있다면, 현실에 반영이 될 것이다. 예를 들어 당신과 나 그리고 바이러스 X는 국제 유대인 음모설따위는 존재하지 않는다고 동의한다.우리는 다행히도 요즘은 보기 힘든  사악한 바이러스 N에 동의하지 않는다. 다른방식으로 말해보자면, 폭스 뉴스가 하켄크로이츠를 로고로 내세우고 빌 오라일리에게 시온 의정서에 대해 독설을 날리라고 한다면, 시청률은 아마 떨어질 것이다.

'현실과 일관된 관계가 없다'는 말은 이렇다. 어떤 이유에서든 간에, 진실보다 보수적 정신 안에서 오류를 재현하는 것이 더 낫다면, 보수주의자들은 그 오류를 믿게 될 것이다. 진리가 좀 더 순응적이면 그들은 진리를 믿게 될 것이다. 어떻게 오류가 진실보다 더 나은 이야기를 만들 수 있는지 폭스뉴스에서 보는 것은 꽤 쉽다. 따라서 그 근원에서 진실을 얻는거 당연히도 어려울 것이다.

정리하자면 의심을 향한 첫단계는 쉽다. 단지 진보주의자들이 신뢰하는 기관들 또한 같은 방식으로 잘못될 수 있다는 것을 스스로에게 의심을 하면 될 것이다. 만약 NPR이 폭스뉴스와 마찬가지로 오류를 재현할 수 있다면, 우리는 실제로 Y 바이러스를 보고 있는 것이다. 바이러스 X가 틀렸을 때 바이러스 Y가 옳을 수도 있고, 바이러스 X가 옳을 때 옳을 수도 있고, 바이러스 X가 틀렸을 때 틀린 것일 수도 있다. 이 둘이 현실과 일관된 관계가 없는 이상 이 둘 서로 또한 일관된 관계가 없다.

이 이론에는 흥미로울만한 대칭성이 존재한다. 그것은 바로 (세계와 역사의 기준에 의해) 어느 사회의 한쪽이 그다지 달라보이지 않는 다른 사회의 한쪽과 대칭을 이루어 비교적 정상적으로 보이게 한다는 것이다. 하지만 실제는 전혀 그렇지 않다.

게다가 이점은 아까 얘기했던 기괴한 모순이 담긴 마멧의 이야기와 맞아떨어진다. 거기에다 이제 마멧은, 그의 새로운 보수적인 견해를 다음과 같이 전하고 있다.

>정부의 역할은 무엇인가? 음, 추상적인 개념에서, 내 왕년에는 정부가 좋은 것이라 생각했지만, 여태까지 내가 봐온바에 따르면, 정부의 개입은 슬픔보다 더한 고통을 남겨주었다.

하지만 아까 그는 우리에게 다음과 같이 말했다.

>60년대의 어린 시절, 나는 정부가 부패하고, 정부의 사업이 착취적이며, 선천적으로 사람들은 마음씨가 좋다는 것을 진리로 받아들였다.

60년대의 어린시절, 나는 정부가 나쁘다는 것을 진리로 받아들였지만...지금은 정부가 나쁘다? 지금 누가 누구한테 [사도 바울의 회심](https://en.wikipedia.org/wiki/Conversion_of_Paul_the_Apostle)에  [급커브](https://en.wikipedia.org/wiki/Doughnut_(driving))를 돌리는 꼴인가?  

오늘날 미국 정치의 매혹적인 사실 중 하나는 진보와 보수 모두 정부를 싫어한다는 것이다. 그들은 단지 정부의 각기다른 부분들을 싫어하고, 그외 부분들은 사랑하고 소중히 여긴다. 예를 들어 외교정책에서는 진보주의자들이 국방부를 싫어하고, 국무부를 사랑하고 아낀다. 보수주의자들은 국무부를 싫어하고, 국방부를 사랑하고 소중히 여긴다.

이것이 우리의 바이러스 X-Y 이론과 얼마나 잘 들어맞는지를 보라. 워싱턴 주변에는 많은 지대들이 있는데, 그 중 일부는 바이러스 X 기계의 일부이고, 다른 일부는 바이러스 Y에 의해 영구히 감염되어 있다. 벨트웨이 지역 밖에는 바이러스에 감염되어 침을 흘리는 좀비 유권자들의 무리가 있다. X 좀비들은 Y 기관을 싫어하고, Y 좀비들은 X 기관을 싫어한다.

그러나 그들 중 누구도 워싱턴 전체를 싫어하지는 않는다. 그래서 그들은 결코 연합하여 그들의 정치기계 자체를 파괴할 수 없으며, 그 기계체제 전체는 안정화되어 있다. 이게 얼마나 아름다운지 보이는가? 유권자들을 경쟁적이지만 협력적인 두 정당으로 분리시킴으로써, 둘 중 어느 쪽도 상대방을 파괴할 수 없는 양당 체제는 그 시스템이 사라진다면 국민들의 삶이 얼마나 더 행복해질지는 상관하지 않은 채 무한히 살아남을 수 있는 정부를 만들어낸다.

이것이 우리의 미스터리의 끝에 달려 있는 과실이다. 만일 당신이 보수주의자가 되지않되 진보가 되지않는 방법을 안다면, 당신은 정말로 정부에 대항하는 방법을 알아낼 것이다. 적어도, 당신은 이 양당체제 안의  정치인들, 사회운동, 기관들 중 그 어느 것도 여러분의 지지를 받을 만한 가치가 없다고 결정할 수 있을 것이다. 나를 믿는가? 이 깨달음은 당신을 해방시켜주는 경험이 될 것이다.
     

하지만 아직 우리는 이 단계에 오르지 못했다. 우리는 실질적으로 진보주의를 의심해야할 만한 진정한 이유를 찾지 못했다. 사소한 실수들-타임스든 뭐든 간에 약간의 팩트체크 실수들은 계산에 넣지 마세요. 왜냐하면 진보주의는 기본적으로 옳고 보수주의는 기본적으로 틀리다는 당신의 확신에 대해 아무것도 하지 않기 때문입니다. 몇 가지 별난 점이 있더라도 보수의 치유책으로서의 진보주의는 지킬 가치가 있다. 항체가 아닐 수도 있지만, 아마도 Y 바이러스는 적어도 백신일 것이다.

게다가 진보와 보수 운동 사이의 몇 가지 주요한 비대칭성을 간과해 왔습니다. 그들은 서로의 사악한 쌍둥이가 아니다. 그것들은 매우 다른 것이다. 하나는 신용할 수 있고 다른 하나는 신용하지 않을 것이라는 것은 꽤 그럴듯하며, 그 장점들은 모두 진보적인 쪽에 있는 것처럼 보인다.

먼저 진보진영 인사들부터 살펴보겠습니다. 청색국가, 적색국가라는 표현이 말해주듯 오늘날 미국의 진보와 보수는 다른 종족이다. 그들은 무작위로 배포된 의견이 아니다. 그들은 명확한 패턴을 따른다.

제 아내와 저는 몇 주 전에 딸이 하나 있었는데, 그녀가 퇴원하기로 되어 있기 직전에 의사들은 UCSF의 소아 심장학 책임자의 간단한 방문을 필요로 하는 경미한 심장 질환을 발견했습니다. 아주 유쾌한 사람. 그리고 그가 처음으로 한 말 중 하나는, 그의 침상 태도의 일부, 즉 우리를 편안하게 하는 방법이었는데, 조지 W. 부시 대통령에 대한 발언이었다. 어쩐지 그가 우리를 스톡턴에서 온 힉스라고 진단했다면 이런 소음을 내지 않았을 거라는 의심이 든다.

오히려 그 선량한 의사는 우리를 스터프 화이트 피플 라이크 부족의 일원으로 지목했었다.[^1] 이 작은 풍자 사이트는 대략 10분의 1의 시간에 UR의 100배의 교통량을 끌어 모았습니다. 이것은 무언가에 연결되어 있다는 꽤 확실한 신호입니다. 작가 크리스 랜더는 딱 한 가지 농담이 있습니다. 그는 묘사되는 것을 좋아하지 않는 그룹을 묘사하고 있습니다. 그리고 그는 그들이 스스로 선택할 성을 그들에게 할당했습니다.

버닝맨을 다녀온 사람이라면 누구나 증언할 수 있듯이 랜더의 '백인들'은 실로 압도적으로 백인이다. 그러나 동양인, 심지어는 흑인이나 라틴계인 '백인'들도 얼마든지 있다. 사실, 랜더가 지적하듯이, "백인"은 인종 차별주의자와 정반대이다. 그들은 소수민족을 갖고 싶어 안달이다. 그리하여 그들을 "백인"이라고 부르는 유머가 생겨났다. 사실, 통합 고등학교에 다닌 사람이라면 누구나 증언할 수 있듯이, 랜더가 "흰색"이라는 단어를 사용한 것은 거의 미국의 흑인용어인 "너무 하얀색"과 거의 똑같다. "빵"이라는 단어를 추가하면 당신은 그것을 내려놓을 것이다.

이 이상한 사람들은 누구입니까? 간략하게, 그들은 미국의 지배계급이다. 여기 UR에서는 브라만이라고 부릅니다. 브라만 부족은 세습이라기보다는 양자로 되어 있다. 누구나 브라만이 될 수 있고, 사실 당신의 배경이 덜 "백인"수록 더 좋다. 왜냐하면 그것은 당신의 업적이 모두 당신 자신의 것이라는 것을 의미하기 때문이다. 힌두교 원문과 마찬가지로 브라만으로서의 당신의 지위는 돈의 기능이 아니라 학자, 과학자, 예술가, 혹은 공무원으로서의 당신의 성공에 대한 것입니다. 브라만은 정신으로 일하는 사람들이다.

브라만은 말 그대로 통치하는 민족이기 때문에 지배계급이다. 현대 민주주의 체제에서 공공 정책은 일반적으로 브라만들에 의해 공식화되는데, 일반적으로 이 "백인"들이 모이는 것을 좋아하는 NGO에서이다. 그리고 모든 진보주의자가 브라만이고 모든 브라만이 진보주의자는 아니지만, 일반적으로 그 방정식이 따른다.

가장 중요한 것은 브라만의 정체성이 미국 대학 시스템과 불가분의 관계에 있다는 점이다. 만약 당신이 브라만이라면 당신의 지위는 학문적 성공에 의해서, 혹은 어떤 준학파적 성취에 의해서, 책 한 권을 쓰고 지구를 구하는 일 등 어느 정도 부여된다. 그러므로 대부분의 브라만들이 상당히 지적이고 세련되었다는 것은 놀랄 일이 아니다. 그들은 그래야만 한다. 적어도 가짜만은 못 꾸며낸다면 브라만이 아니다.

브라만의 천적은 물론 붉은 주 미국인이다. 나는 이 부족에 다른 힌두 카스트 이름인 '바이지사스'를 사용하곤 했지만, 그들을 타운리스라고 부르는 것이 더 발현적인 것 같다.[^2]진보주의자로서 여러분은 아마도 브라만일 것입니다. 여러분은 이 사람들을 알고 있고, 그들을 좋아하지 않습니다. 뚱뚱하고, 배타적으로 백인이고, 교외에 살거나, 참나무와 크로셰와 미니밴에 빠져있으며, 물론 공화당원인 경향이 있다. 아예 대학에 진학했다면 신입생 다양성 요건을 뚫고 이를 악물었다. 그리고 그들의 작품은 화이트칼라일지는 몰라도 실제 지적 내용은 없다.

(이 부족의 렌즈를 통해 한번 보면 미국 정치가 얼마나 더 단순해지는지가 흥미롭다. 여러분은 제3세계 국가들에서 종종 이것을 볼 수 있습니다. 말하자면, 앙골라 인민 운동과 민주 앙골라 전선이 있을 것입니다. 각자 앙골라 전체 국민의 미래를 위해 일한다고 아래위로 맹세할 것이다. 하지만 APM의 모든 사람들은 오밤보이고, DAF의 모든 사람들은 바콩고라는 것을 알 수 있습니다.)

브라만과 타운시의 지위 관계는 명확하다: 브라만은 더 높고, 타운은 더 낮다. 브라만이 타운시를 싫어할 때 그 태도는 경멸이다. 타운에이들이 브라만을 미워할 때 그 태도는 원한이다. 그 둘은 혼동할 수 없다. 브라만족과 타운족이 층층화된 사투리를 공유한다면, 브라만족은 곡예를 말하고 타운족은 음모를 쓴다.

즉, 브라만이 타운리보다 더 유행하는 것이다. 기본적으로 더 좋은 취향인 브라만의 취향은 타운시를 향해 아래로 흐른다. 20년 전만 해도 '건강식품'은 틈새의 초브라만 기행이었다. 이제 사방에 널려 있다. 교외 거주민들은 에스프레소를 마시고, Whole Foods에서 쇼핑하고, 얼터너티브 록을 듣고, 이름을 대세요.

그래서 우리는 왜 진보주의가 보수주의보다 더 유행하는지 알게 된다. 예를 들어 진보적인 유명인사들은 어디에나 있다. 보수적인 것은 예외다. 비록 많은 진보적인 유명인사들이 그들의 신념에 성실한 것처럼 보이지만, 냉정한 계산은 충분할 것이다. 보노의 홍보 담당자들은 그가 에이즈에 대해 목소리를 높인 것에 대해 기뻐하고 있다. 멜 깁슨의 홍보 담당자들은 그가 유대인들에게 목소리를 높인 것에 대해 기뻐하지 않는다.

그래서 보수에 대해서 의문을 제기할 때 우리 부족 사람들에게 자연스럽고 분별력 있는 사고방식, 즉 적을 공격하고 있는 것입니다. 그리고 적은 실로 만만한 상대다. 사실 적은 의심스러울 정도로 쉽게 밀어 넘어간다.

보수의 전체 라이프사이클을 보세요. 그 모든 것이 악취를 풍긴다. 바이러스 X는 교육을 받지 못한, 일반적으로 지능이 떨어지는 사람들의 마음속에서 복제한다. 사실 타운티족은 히틀러와 무솔리니를 우리에게 준 바로 그 기본 부족이다. 그것들과 같은 그것의 지적 기관들은 별난 재벌들에 의해 지원된 보조된 프린지 신문, TV 채널, 그리고 이상한 싱크탱크들이다. 정부에서 보수의 보루는 사람을 죽이는 것이 목적인 군대, 예를 들어 기업의 로비스트들이 환경을 강간함으로써 책임을 질 수 있는 기관이다.

반면에, 바이러스 Y는 "바이러스"가 정말로 그것의 이름이라면, 미국에서 가장 저명한 서클들, 실제로 세계에서 가장 유명한 것들, 즉 일류 대학들, 위대한 신문들, 록펠러, 카네기, 포드 같은 오래된 재단들에서 복제된다. 침 흘리는 좀비들은 이 나라에서 가장 똑똑하고 가장 성공한 사람들입니다. 정부에서는 세계 평화를 구축하고, 환경을 보호하며, 가난한 사람들을 돌보고, 아이들을 교육한다.

문제의 진실은 진보주의가 미국의 주류 전통이라는 것이다. 이것은 그것이 지난 200년 동안, 심지어 지난 50년 동안 변하지 않았다는 것을 말하는 것이 아닙니다. 그러나 나라살이를 하는 동안 하버드에서 가르치고 공부한 사상과 이상을 살펴보면 지금까지는 순조로운 진행을 보았고, 폭력적인 역전이나 심지어는 변곡점까지도 보지 못했으며, 결국 낡은 근대적 진보주의로 끝나게 된다. 물론, "미국의 전통"은 뉴잉글랜드의 전통을 의미합니다. 남북전쟁이 다르게 전개되었다면, 상황은 다르게 흘러갔을 수도 있습니다. 그러나 150년 전에 나다니엘 호손(Nathaniel Hawthorne)이 히피 공동체에 관한 소설을 썼다는 것을 알게 되면, 태양 아래서는 새로운 것이 없다는 것을 깨닫게 된다.

마키아벨리가 말한 바와 같이, 왕을 치거든 죽이려고 쳐라.[^3]겨우 50년 된, 그리고 수많은 허름한 뿌리를 가진 보수주의는 조롱과 경시, 경멸을 받을 수 있다. 보수 비판과 진보 비판의 차이는 모르몬교 비판과 기독교 비판의 차이입니다. 진보주의를 조금만 의심해도 안 된다. 대승적 차원에서 의심해야 한다.

보수가 부패하고 망상적인 전통이라고 하는 것은, 어느 정도의 '바이러스 X'에 지나지 않는다고 하는 것은, 미국의 편에 선 진드기, 일탈, 낙태, 고쳐야 할 오류라고 하는 것입니다. 교육의 실패, 리더십의 실패, 진보의 실패. 정말 작은 일이지.

진보주의를 의심하는 것은 미국의 생각 자체를 의심하는 것이다. 왜냐하면 진보주의는 그 생각이 결국 끝난 것이기 때문이다. 진보주의가 '바이러스 Y'라면 미국 자체도 감염된다. 그것에 대한 치료법은 무엇인가? 그것은 이상하고 끔찍한 생각, 즉 종말론의 약속이다.

그럼에도 불구하고 그것은 끔찍한 종류의 이치에 맞습니다. 우선, 만약 당신이 정신 바이러스라면, 어떤 전통을 선택해서 감염시키겠습니까? 미국 사상의 중심 조류, 아니면 어떤 베니티드 백워터? 브라만족, 아니면 타운족? 유행하는 사람들, 아니면 유행하지 않는 사람들?

여러분의 DNA를 뉴욕 타임즈에 복사하면 2, 30년 후에 폭스 뉴스로 흘러가게 될 것입니다. 폭스 뉴스로 복사하면 다음 선거에 영향을 미칠지도 몰라 아니면 두 개. 하지만 그게 얼마나 오래가는 거야? 조지 W 부시에게 지적으로 감동을 받는 사람이 얼마나 될까?(강제는 계산에 넣지 않는다.)

브라만(나는 당신이 브라만이라고 가정할 것이다)으로서 당신은 바이러스 Y 안에 산다. 당신은 좀비 중의 한 명입니다. 여러분의 세계관은 하버드, 타임즈, 그리고 나머지 것들은 데이비드 마멧의 시대에 설립자라고 부르곤 했습니다. 정부, 역사, 과학, 사회에 대해 당신이 알고 있는 모든 것들은 이 기관들에 의해 걸러졌습니다. 분명히 이 서술은 모순되지 않는다. 하지만 과연 그것이 사실일까요?

음, 대부분 모순되지 않아요. 아주 잘 조립되어 있습니다. 하지만, 어떤 곳에서는, 여러분이 정말 자세히 본다면, 여러분은 실오라기 같은 것을 볼 수 있다고 생각해요. 트루먼 쇼의 짐 캐리처럼 세상의 가장자리로 항해할 필요는 없다. 우선, 의심스러운 근육을 간지럽히고 약간 경련을 일으키는 데 필요한 것은, 딱 들어맞지 않는 몇 가지 세부사항이다.

세 가지 질문으로 시작하겠습니다. 우리는 작은 게임을 할 것입니다. 여러분은 진보적인 답을 생각해내려고 하고, 저는 진보적이지 않은 답을 생각해내려고 합니다. 어느 쪽이 더 말이 되는지 두고 보자.

이런 질문들이 진보적인 답변이 없다는 뜻은 아닙니다, 왜냐하면 그렇거든요. 모든 것이 보수적인 답변이 있듯이 진보적인 답변이 있습니다. 답안을 작성할 진보진영이 부족함이 없다. 그런데 이런 질문들이 만족스러운 진보적인 답변들을 가지고 있다고 생각하지 않습니다. 물론 이것을 당신 자신의 좋은 취향을 가지고 스스로 판단해야 할 것이다.

첫째: 제3세계는 어떻게 되었는가?

예를 들어, 여기 말라리아와의 싸움에 관한 타임즈 기사가 있다. 종종 정치인과 마찬가지로, 기자들은 그들의 진짜 관심사가 다른 것일 때, 멍한 상태에서 진실을 말한다. 만약 당신이 그 이야기를 읽는다면, 당신은 내가 한 것과 같은 놀라운 그래프를 알아차릴 수 있을 것이다.

>그리고 세상은 바뀌었다. 1960년대 이전에, 식민지 정부와 기업들은 말라리아와 싸웠다. 왜냐하면 그들의 관리들이 나이지리아의 언덕 정거장이나 베트남의 마블 산맥과 같은 외진 전초기지에서 종종 살았기 때문이다. 독립 운동은 자유로 이어졌지만 내전, 빈곤, 부패한 정부, 의료 붕괴로 이어지는 경우도 많았다.

그 마지막 문장에 초점을 맞추자. 독립 운동은 자유로 이어졌지만 내전, 빈곤, 부패한 정부, 의료 붕괴로 이어지는 경우도 많았다.

나는 종종 내가 목성 행성에서 온 외계인이라고 상상하는 것이 유용하다고 생각한다. 만약 내가 이 문장을 읽는다면, 나는 이렇게 묻고 싶다: 이 자유란 단어는 무엇인가? 이 작가가 말하는 자유란, 정확히 어떤 것인가? 특히 내전, 빈곤, 부패한 정부라는 맥락에서?

여기서 우리가 보는 것은, 작가가 분명히 좋은 것이라고 믿고 있는 독립 운동이, 이 기이한 추상화 외에도, 매우 구체적이고 매우 끔찍한 결과를 초래했다는 것입니다. 분명히 이 특정한 맥락에서 자유가 무엇을 의미하든지 간에 그것은 너무나 큰 긍정적이어서 그것을 내란, 가난, 부패한 정부, 의료의 붕괴에 보태도 그 결과는 여전히 제로를 넘어선다.

이상하지 않나요? 이 특별한 산수를 다시 찾고 싶지 않을까요? 하지만 우리는 그럴 수 없습니다. 만약 우리가 식민지 정부와 기업(이것이 무엇이든 간에)이 자유가 없는 독립 운동보다 더 바람직했다고 가정한다면, 우리는 진보적인 입장에서 이 같은 자유를 창조했기 때문입니다.

사실상 진보적 성향에서 벗어나 있을 뿐만 아니라 보수적 성향에서도 벗어났습니다. 아무도 이것을 믿지 않는다. 여러분은 폭스 뉴스나 townhall.com이나, 식민주의라고 주장하는 가장 형편없는 출판물들 말고는 아무도 찾을 수 없을 것입니다. 그 본질적인 자유 부재와 이상하게 효과적인 말라리아 통제를 가지고 있습니다(필자가 실제로 말할 것도 없이, 이것은 단지 악한 식민지 중첩의 이기적인 목적을 위해서만 전달되었다는 것을 암시합니다).), 자유, 말라리아, 내전 등과 함께 어떤 면에서든 후기 식민주의보다 우위에 있었다.

그리고 이 단어가 정확히 무엇인가요? 독립이란 단어는? 자유와 같은 의미인 것 같은데, 그런데도 이상하다. 예를 들어, CFR의 미셸 가빈에 의한 이 포스트 오피드를 생각해 보자. 이는 다음과 같은 흥미로운 선으로 시작한다.

>1980년 짐바브웨가 독립국이 되었을 때 아프리카의 미래에 대한 국제적 낙관론의 초점이었다. 오늘날 짐바브웨는 한 나라의 바구니 사건이다.

목성에서 떨어진 외계인 모자를 다시 쓰고, 다음과 같은 구절을 생각해 보자. 짐바브웨가 1980년에 독립국이 되었을 때…

그녀가 보통 말하는 영어에서, 독립적인 단어는 "아니오"를 의미하는 접두사와 "의존적"을 의미하는 접미사로 구성되어 있다. 그러니까 예를 들어서 미국이 독립했을 때 어떤 외부 정당도 자기 정부에 자금을 지원하거나 통제하고 있지 않다는 것을 의미했습니다. 내 딸이 독립한다면, 그것은 그녀가 세상에서 스스로 결정을 내리고 있다는 것을 의미할 것이고, 나는 세 시간마다 그녀에게 한 병씩 줄 필요가 없었다.

그러나 짐바브웨의 경우 이 말이 이상하게 바뀌어 거의 정반대의 의미를 띠게 된 것 같다. La 위키에서:

>영국으로부터 로디지아의 일방적인 독립 선언(UDI)은 1965년 11월 11일 당시 영국 식민지에서 흑인의 다수결 원칙에 반대한 이언 스미스의 행정부에 의해 서명되었다. 영국으로부터의 독립을 선언했지만 엘리자베스 2세 여왕에 대한 충성을 유지했다. 영국 정부와 영연방, 유엔은 이번 조치가 불법이라고 규탄했습니다. 로디지아는 1979년부터 1980년까지 짧은 기간 동안 영국의 사실상의 지배와 드 쥬레 영국의 지배로 되돌아가다가 1980년 짐바브웨로서 독립을 되찾았다.

그래서 이상하게도, 현재 짐바브웨로 알려진 이 나라는 미국이 1776년에 독립을 선언했던 만큼 1965년에 독립을 선언했다. 그러나 전자는 진정한 독립이 아니라 오히려 불법적인 독립이었다. 진정한 합법적 독립을 얻기 위해 짐바브웨로 알려진 이 나라는 우선 영국의 지배로 되돌아가야 했고, 즉 불법적인 독립을 포기해야 했다. 아직 혼란스러우세요? 더 나아지고 있습니다.

>1980년 짐바브웨가 독립국이 되었을 때 아프리카의 미래에 대한 국제적 낙관론의 초점이었다. 오늘날 짐바브웨는 한 나라의 바구니 사건이다. 지난 10년 동안 로버트 무가베 대통령과 집권당이 자신들의 권력에 대한 도전을 용납하지 않는 바람에 짐바브웨 경제 및 정치체제의 가장 효과적인 작업을 조직적으로 해체하고 이를 부패, 노골적인 후원, 억압의 구조로 대체하게 되었다.

그래서: 자유 짐바브웨의 독립된 통치자들은 그들의 권력에 대한 도전을 용납하지 않았다. 따라서 가빈(Gavin, 1980년에 아마도 한 두 병이 필요했을 것이다) 여사와 그녀의 우유가 가지고 있는 국제적 낙관주의는 비관론에 자리를 내주었고, 그 장소는 이제 바스켓 케이스가 되었다. 그리고 누가 좋은 무가베 대통령의 권력에 도전했을까? 아마도 짐바브웨의 경제 및 정치 시스템의 가장 효과적인 작업을 해체할 의도가 없었던 것으로 추정되며, 이는 가빈 씨와 그녀의 불유불능의 우애를 얻는 것이다. 이 독립성은 보시다시피 매우 호기심이 많은 것입니다.

스스로 일을 하고 절대 병도 필요치 않다는 의미에서, 사실 세계에는 눈에 띄게 독립된 나라가 하나 있다. 소말릴란드라고 하는데, 국제사회에서 누구에게도 인정받지 못하고 있습니다. 소말릴란드의 수도인 하르게이사를 위한 위키백과 페이지는 의도하지 않은 높은 코미디의 영광스러운 수준을 달성합니다.

>외국 정부의 원조는 존재하지 않아 아프리카에서는 대외원조에 대한 의존도가 낮아 이례적이었다. 소말릴란드는 독립국가로서 탈사실화 되어 있지만 국제적으로 (법적으로) 인정받지 못하고 있다. 따라서 소말릴란드 정부는 IMF와 세계은행의 원조에 접근할 수 없다.

이 모든 게 상당히 궁금하지 않습니까? 짐 캐리가 요트를 세상 가장자리의 매트 그림 속으로 쾅쾅 들이치는 장면이 조금이라도 생각나지 않는가?

둘째: 민족주의란 무엇인가? 그리고 그것이 좋은가, 나쁜가?

이 질문은 질문1과 다소 유사하다. 제가 존경하는 진보 블로거가 '호찌민은 민족주의자'라는 오프핸드 코멘트를 했을 때 떠올렸다. "그럼," 나는 생각하고 있는 자신을 발견했다. "그리고 팻 부캐넌도 마찬가지야." 그때가 아니었지만, 이 작은 모티브인 데스칼리어를 구했고 지금 다시 꺼내지 않고는 못 배깁니다, 나쁜 물고기처럼.

독립과 달리, 나는 모든 사람들이 민족주의의 정의에 거의 동의한다고 생각한다. 민족주의(國民主義, )는 공통의 언어적, 민족적, 인종적 유산의 사람들이 하나의 정치적 실체로서 집단적으로 행동할 필요성을 느끼는 때를 말한다. 독일 민족주의는 독일인이 할 때, 베트남 민족주의는 베트남인이 할 때, 흑인 민족주의는 아프리카계 미국인이 할 때, 미국의 민족주의는 팻 부캐넌이 할 때이다.

그리고 여기서 협정이 끝난다. La 위키의 첫 단락은 난독화의 걸작이다.

>민족주의(國民主義, Nationalism)는 보통 민족이나 문화면에서 정의되는 민족이 역사나 공동운명에 기초하여 독립적 또는 자율적 정치공동체를 구성할 권리를 갖는다고 주장하는 교리나 정치운동을 가리키는 용어이다. 대부분의 민족주의자들은 국가의 국경이 국가의 국경과 일치해야 한다고 믿는다. 그러나 최근 민족주의자들은 그 호혜적 가치를 위해 '공조'라는 개념을 거부해 왔다. 현대 민족주의자들은 국가가 단일 국가에 의해 통치되어야지, 국가가 단일 국가에 의해 통치되어야 한다고 주장할 것이다. 때때로 민족주의적인 노력은 우월주의나 제국주의 때문에 골치를 앓을 수 있다. 20세기 파시스트 운동에 의해 전파된 것과 같은 이러한 전 민족주의적인 노력은 여전히 국적이 정체성의 가장 중요한 측면이라는 민족주의 개념을 가지고 있는 반면, 그들 중 일부는 인종이나 유전학적으로 부정확하게 국가를 정의하려고 시도했다. 다행히도, 현대 민족주의자들은 이들 집단의 인종차별주의적 우월주의를 거부하고, 민족 정체성이 민족에 대한 생물학적 애착을 대체한다고 확신하고 있다.

그들 사이의 모든 것은 내가 알 수 있는 한 순전히 허튼소리이지만, 첫 문장과 마지막 문장의 직접적인 모순에 주목하라. 민족적 정체성이 민족에 대한 생물학적 애착을 대체한다고 믿는다면 어떻게 민족주의자가 될 수 있겠는가? 민족주의가 인종주의적 우월주의에 시달리지 않는다면 어떤 의미에서 민족주의란 말인가.

제가 체코인이며 오스트리아-헝가리에 살고 있다면, 제 조국에 대한 권리가 있나요? 받을 때까지 폭력과 테러와 폭탄을 만들어야 할까요? 만약 내가 독일인이고 체코슬로바키아에 산다면? 폭력과 테러와 폭탄을 만들어야 할까요?

많은 독일인들이 20년대와 30년대에 이 이상한 점을 알아차렸다. 그들은 미국과 그녀의 친구들이 국가적 자결, 즉 당신이 우연히 독일인이 되지 않는 한 대단히 헌신적이라는 것을 알아차렸다. 체코 민족주의는 좋았어. 아주 좋았어. 독일의 민족주의는 나빴어. 아주 나빴어.

일단 캔버스에서 이 작은 꿰미를 찾기 시작하면, 어디에서나 발견하게 됩니다. 흑인 민족주의자가 되는 것은 좋은, 아주 좋은 일이다. 래퍼 라이트(Light)에서 우리는 진보주의와 흑인 민족주의 사이의 친밀함을 보아왔다. 톰 울프가 잘 보여 주었다. 실제로, 미국의 모든 유명한 대학에는 학생들이 본질적으로 흑인 민족주의를 전공할 수 있는 학과가 있다.

반면에 남부 민족주의자가 되는 것은 나쁘다, 매우 나쁘다. 남방 민족주의와의 어떤 연관성이라도 즉각적으로 하나의 파리아를 낳는다. 물론 남부 민족주의자들은 죄를 지었다. 하지만 역시 흑인 민족주의자들 역시 마찬가지입니다. 흑인이든 백인이든 미국인이든 흑인의 팬터, 이슬람의 국가, 혹은 심지어 선량한 신부의 활동에 정말로 더 잘 살고 있는가? 라이트?

마찬가지로 베트남 국수주의자가 되는 것도 좋다. 독일 민족주의자, 혹은 영국 민족주의자, 혹은 심지어 프랑스 민족주의자가 되는 것은 여전히 나쁘다. 독일인, 영국인, 프랑스인은 모든 인류의 공통된 운명을 믿게 되어 있다. 베트남인이나 멕시코인이나 체코인은 자유롭게 베트남인이나 멕시코인, 체코인의 공동운명체를 믿고 있다.(사실 체코인에 대해서는 잘 모르겠다. 이게 바뀌었을지도 몰라요.)

이게 말이 됩니까? 말도 안 되는 소리야?

이 과목은 너무 까다롭기 때문에, 나는 그것에 대한 내 감정을 흘려보낼 것이다. 나는 어떤 종류의 민족주의도 믿지 않는다. 물론, 자코바이트인이고 뭐고, 나 또한 스트라포드의 자치구를 믿으니까, 당신은 나에게서 당신의 헌법적 조언을 얻고 싶지 않을지도 모른다.

셋째: 나치가 뭐가 그리 나쁜가?

천만 명을 죽였어 안됐군요. 수백만 명의 민간인 학살을 옹호하는 것은 정말 있을 수 없는 일입니다 .

한편, 니콜슨 베이커의 신간 '인간 연기'를 정말 추천합니다. 베이커는 진보적이고 평화주의자이며 (그의 이전 업적은 부시 대통령을 암살하는 환상을 가진 소설이었다) 그리고 인간 연기 드럼이 당신에게 주는 것은 특정한 메시지가 아니라, 내가 계속 말하는 것과 같은 것이다: 그림의 조각들이 서로 맞지 않는다. 거의 맞긴 맞는데 잘 안 맞네요. 베이커의 책의 천재성은 단순히 그림이 어울리지 않는 것을 보여주고, 분석을 당신에게 맡긴다는 것이다.

예를 들어, 우리는 나치들이 대량학살을 저질렀기 때문에 나쁘다고 배웁니다. 재치있게 말하자면, 홀로코스트를 저질렀기 때문입니다. 반면에 (a): 우리를 포함한 나치에 대항하는 어떤 정당도 유태인이나 홀로코스트에 대해 많은 것을 주지 않은 것 같다; (b) 우리 쪽의 정당 중 하나는 당시 대량 살인에 대한 기록이 알려졌고 적어도 나치만큼 끔찍했던 소비에트 연방이었다.

그리고 물론 (c) : 연합군은 독일과 일본 민간인의 공중 소각에서 긍정적으로 폭로를 했다. 6백만 명을 죽이지 않았지만 한두 명을 죽였습니다. 이런 부분에 대해서 군사적으로 변명하는 부분이 있었지만 상당히 경색된 측면이 있었습니다. 그것은 (물론 적 민간인으로 본) 유대인들을 살해한 나치의 변명보다 나았다. 사실, 훨씬 더 좋았어요. 그런데 많이 좋아졌나요? 잘 모르겠어요.

그리고 베이커가 언급하지 않듯이, 우리의 영웅인 연합군도 전쟁 후 러시아 난민 100만 명을 수용소로 추방하거나, 수십만 명의 독일군 포로를 소련에 노예 노동자로 빌려주는 것에 대해 거리낌이 없었다. 제2차 세계대전을 인권전쟁으로 보는 발상은 그야말로 역사학적이다. 안 맞아요. 나치 인권침해가 지금 우리가 살고 있는 세상을 창조한 전쟁의 동기가 아니었다면 - 무엇이었을까?

더군다나 오늘날 미국의 외교정책을 당연히 비판하고 있는 베이커는 이라크와 독일에도 똑같은 기준을 적용하려 할 때 혼란밖에 보지 못한다. 아부그라이브가 이라크에 무력으로 민주주의를 강요하는 데 가교할 수 없는 장애물이라면 드레스덴이나 함부르크, 독일은 어떨까. 확실히 수만 명을 산 채로 태우는 것이, 가짜 전선을 쓰고 우스꽝스러운 모자를 쓰고 상자 위에 서게 하는 것보다 더 나쁘단 말인가? 아니면 이라크가 독일과 다를 뿐인가? 하지만 그건 인종차별이겠죠?

이를 넘어서면 파시스트 대량살해 대 마르크스주의 대량살해라는 처사에 있어서 독특한 비대칭성이 나타난다. 두 이데올로기 모두 분명히 대량 살인의 역사를 가지고 있다. 만약 숫자가 중요하다면, 왜 그렇게 하지 않을까요?— 마르크시즘은 규모 순으로 앞서 있다. 그러나 어찌된 일인지 오늘날 파시즘이나 그것을 연상시키는 것은 순수한 독이고 손댈 수 없는 것이지만 반면에 마르크스주의는 기껏해야 페카딜로의 일종인 것이다. 존 즈미락은 여기에 대한 멋진 패러디를 보여주는데, 내가 아직 로베르토 볼라뇨를 읽지 않은 동안, 그 리뷰들은 꽤 빛을 발하고 있다.

소련도, 제3제국도 오늘날 우리와 함께 있지 않지만 가장 최근의 역사적 예는 북한과 남아프리카이다. 아파르트헤이트인 남아프리카는 느슨했지만 여전히 나치즘과의 연관성을 알아볼 수 있는 반면, 북한은 분명히 어느 정도 스탈린주의적이다. 나는 국경 울타리가 이민자들을 막기 위해 만들어진 남아프리카가 북한보다 더 나쁜 인권침해국이었다는 것을 주장하고 싶은 모든 사람들을 환영한다. 북한 전체가 감옥으로 변했다. 그럼에도 불구하고 우리는 북한과 같은 비대칭성을 봅니다. 즉, 남아프리카에 대한 순수한 적대감입니다. 만약 뉴욕 필하모닉이 양국의 신뢰를 구축하기 위해 프리토리아를 방문하는 것을 상상할 수 있다면, 당신은 볼라뇨울드에 확고히 있다.

다시 말하지만, 이건 정말 이상해. 민족주의와 마찬가지로 각각의 개별적인 사례도 그 나름의 용어로 설명될 수 있다. 모든 사건을 종합해 보면 이중잣대가 도처에 널려 있다. 그럼에도 불구하고 모순은 무작위로 보이지 않는다. 나치가 가지고 있고 소련이 가지고 있지 않거나, 남아공 사람들이 가지고 있고, 북한 사람들이 가지고 있지 않은 신비스러운 X 요인이 있는 것 같다. 그 치료는 X에 의해서만 이루어지는 것이 아니라 X+인권일 수도 있지만 분명히 단순한 인권이 아니다. 그런데도 설명에는 X가 나타나지 않는다.

X는 나치가 '우파'이고 소련이 '좌파'라는 것과 관련이 있는 듯하다. 프랑스 사람들이 말하길: pas d'ennemis à gookhe, pas d'amis à 드로우이트.[^4]  그런데 왜? '우파'와 '좌파'는 무슨 의미까지 있는 것일까. 소련과 나치 체제가 모두 전체주의 독재체제가 아니었던가. 공산주의가 '너무 뜨겁다', 파시즘이 '너무 춥다', 자유민주주의가 '그저 옳다'면 공산주의와 파시즘을 동등하게 반대하면 어떨까. 사실, 전자는 적어도 1945년 이후 훨씬 더 성공적이기 때문에, 여러분은 사람들이 그것에 대해 더 걱정하게 될 것이라고 생각할 것입니다.

다시 말하지만 우리는 순수한 혼란에 빠져 있다. 수평선이 캔버스로 이루어진다는 것은 도저히 있을 수 없는 일이다. 그럼에도 불구하고 우리 보트는 충돌했고, 큰 바가지를 남겼습니다.

[^1]:스터프 화이트 피플 라이크 부족을 지칭하기 위해 이니셜리즘 "SWPL"(스위플로 발음)을 사용하는 것이 일반화되었다.
[^2]:Moldbug는 나중에 이 그룹에 대해 더 나은 용어를 만들었다. 남아프리카의 아프리케너족과 유추하여 아메리케너족. 그가 <외국의 영토를 점령하고 통치하는 방법>에 다음과 같이 적고 있다. 


    >그들의 어휘적 비유처럼, 아메리카네르족은 유럽 주식의 문화 집단이지만, 그들의 현대 유럽의 어떤 집단과도 쉽게 연결될 수 없다.

[^3]:   이 제형은 랠프 왈도 에머슨에 의한 것으로, 올리버 웬델 홈즈에 의해 대중화되었다. 마키아벨리의 왕자에 영감을 준 인용문은 다음과 같다. 

    > 이 말을 듣고, 사람들은 더 가벼운 상처와 더 심각한 상처로 복수할 수 있기 때문에, 사람들은 잘 치료받거나 으스러져야 한다고 말해야 한다. 그러므로 사람에게 해야 할 상처는 복수를 두려워하지 않는 그런 종류의 것이어야 한다.

[^4]: 보통 영어로 "왼쪽에는 적이 없고, 오른쪽에는 친구가 없다"라고 번역되어 있다.