---
title: "오픈 마인드 진보에게 보내는 공개서한(1)"
author: 'MENCIUS MOLDBUG'
date: '2020-12-16'
slug: 오픈-마인드-진보에게-보내는-공개서한
categories: []
tags:
  - NRx
  - 반동주의
---
미완성 번역

# 1장: 캔버스로 만든 수평선

당신은 오픈마인드를 가진 진보주의자인가? 본인 스스로 그런쪽이 아닐 수도 있겠지만 적어도 당신의 친구들중에선 그런 오픈마인드를 가진 사람이 있을 것이다. 이 글은 당신이나 혹은 그들이나 오픈마인드를 가진 진보들을 위한 글이다.  아마 이글은  나의 블로그, [Unqualified Reservations](https://www.unqualified-reservations.org/)를 소개하는 일종의 입문서 역할이라 보면 되겠다.

만약 당신이 오픈마인드 진보주의자라면 아마 가톨릭 신자는 아닐 것이다 (또한 당신은교황이라는 개념을 진지하게 생각하지도 않을 것이다). 가톨릭 신자들한테 공개 편지를 써서, 로마의 음흉한 지배로부터 그들의 생각을 해방시킬 수 있게 설득하는 것을 상상해보자. 이런 방식은 구식이기도 하겠지만, 그무엇보다도, 어떻게 시작하겠냐는게 관건이겠다. 하지만 이곳 UR(Unqualified Reservation)에서는 구식이 되는 것을 결코 두려워하지 않는다. 그리고 그 시작에 관해서는, 우리는 이미 알고 있다.

진보주의자가 되는 것은 가톨릭 신자가 되는 것과 같을까? 안될게 뭐가 있나?  가톨릭과 진보주의 둘다 일련의 믿음을 통해 세상을 이해하는 방식 이다. 이 믿음들은 사실일 수도 있고, 거짓일 수도 있고, 거짓일 만큼 충분히 이치에 맞지 않는 [헛소리](https://www.unqualified-reservations.org/archive/stove/)일 수도 있다. 오픈마인드 진보주의자(혹은 오픈마인드 가톨릭 신자)로서, 당신은 당신이 가지고 있는 모든 신념이 진실이라고 생각하겠지만 , 아마 약간의 온화한 도움이 함께라면 그 신념들을 다시 생각해볼 용의도 있을 것이다.

가톨릭과 진보주의 사이에는 다음과 같은 큰 차이가 있다. 천주교는 이른바 '종교'다. 종교의 핵심 신념은 정신 세계에 대한 주장인데, 이 주장은 가톨릭 신자(물론 교황을 제외하고)들 스스로 경험한 바가 없다. 반면에 진보적인 믿음은 현실 세계, 즉 정부, 역사, 경제, 사회에 대한 주장인 경향이 있다. 이러한 것들은, 성 삼위일체와는 달리, 우리 모두가 직접 경험하는 현상들이다.

그런데 그게 과연 진실일까? 우리 대부분은 정부를 위해 일한 적도 없고, 정부가 하는 일의 아주 작은 부분만 봐온 사람들이다. 역사는 책에서 나온 것이다. 책에서 나온 역사라는게 성경이 설명하는 방식과는 다르다, 아니면 그게  맞을지도? 우리의 경제학에 대한 개인적인 경험은 무엇인가? 휘발유 가격인가? 그외 기타  등등... 당신의 삶이 길고 상당히 특이한게 아니라면, 나는 당신이 정부, 역사 등에 대한 위대한 의문들에 대해 깊히 고려해보지 않았을거라  본다. 내 사상을 보면 확실히 그렇지 않으니까.

물론 흔히들 진보사상의 상당 부분은 순수이성의 산물이라고 일컬어지고 있다. 그런가? 토마스 아퀴나스는 순수이성으로부터 가톨릭을 파생시켰다. 존 롤스는 순수 이성으로부터 진보주의를 이끌어냈다. 적어도 그들 중 한 명은 실수를 했을 것이다. 아니면 둘 다 그랬을 수도 있다. 그들의 저작들을 직접 확인해보았는가? 한 가지 나쁜 변수가 당신의 모든 증거를 무너뜨릴 것이다.

그리고 정말 그게 맞는 말일까? 당신이 진보인 이유가 아무것도 믿지 않는 데서 출발했으며("우리는 [허무주의자](https://www.youtube.com/watch?v=Y5J_kao6mwA)다! 우리는 아무것도 믿지 않는다!") 그걸 바탕으로 생각해온게 진보이기때문이라 생각하는가? 물론 나는 당신의 경험을 대변할 수는 없지만, 당신의 부모가 진보주의자였기 때문에 진보주의자이거나, 아니면 어떤 책이나 선생을 통해서라던지 혹은 다른 지적인 경험에 의해 진보로 전향되었을 것이라 본다. 이런 방식은 바로 가톨릭 신자가 되는 것과 똑같을 수밖에 없다 .

하지만 거기엔 한가지 차이점이 있긴 있다. 가톨릭 신자가 되려면 믿음을 가져야 한다, 왜냐하면 아무도 성령을 직접 본 적이 없으니까. 진보주의자가 되기 위해서는 신뢰가 있어야 한다, 왜냐하면 자신의 세계관이 실제 세계를 정확하게 반영한다 믿고있으니까- 당신 혼자만의 작은 눈으로 보는 경험이 아니라, 인류 전체의 경험으로서.

하지만 당신은 '인류 전체의 경험'이란걸 공유해보지 못했다. 당신은 단지 그것으로부터 편집된 글들, 녹음물, 비디오의 말뭉치를 읽고 듣고 보았을 뿐이다. 그리고 이런 것들이 도대체 누구에 의해 편찬되었는가? 거기에서부터 신뢰가 나오는건데 이에대한 설명이 좀 더 필요하다.

나는 진보주의자는 아니지만, 과거에 진보주의자로 자랐다. 나는 샌프란시스코에 살고 있고, 외교관 부모가정에서 자랐으며, 브라운 대학에 진학했으며, 80년대 중반부터 [Tom's of Maine](https://en.wikipedia.org/wiki/Tom%27s_of_Maine)으로 이를 닦았다. 내게 일어난 일이란, 난 신뢰를 잃어버렸다는 것이다.

[데이비드 마멧](https://en.wikipedia.org/wiki/David_Mamet)도 신뢰를 잃었다. 그가 빌리지 보이스지에 쓴 [에세이](http://www.villagevoice.com/news/david-mamet-why-i-am-no-longer-a-brain-dead-liberal-6429407)는 읽어볼만 하다, 세계에서 가장 유명한 극작가가 더 이상 자신이 '뇌절한 리버럴'이 아니라고 선언하는 '충격적인' 사실만 볼때에는 말이다. 그 기사에 달린 댓글은 500여 개다. 내가 놓쳤을지도 모르는 부분이지만 마멧이 깨달음을 얻었다거나 하는 긍정적인 댓글은 보이지 않는다.

물론 마멧은 전형적인 마멧이다. 그는 충격에 빠진 것이지 전향한 것이 아니다.  리버럴이라는 단어조차도, 적어도 오늘날 정치적 이해관계 속에서는 , 모욕적인 언사로 통용된다. 그것은 마치 가톨릭 출신이었던 전향자가 "왜 나는 더 이상 뇌절한 천주교빠가 아닌가"라고 설명하는 것과 같다. 존 스튜어트 밀은 리버럴이었다. 버락 오바마는 진보주의자이고, 당신 또한 진보주의자이다. 예의의 기본 원칙: 사람들이 스스로 부르지 않는 이름을 부르지 말라.

더욱이 마멧은 진보주의만 배척하는 것이 아니다. 그는 보수주의를 지지한다. 하느님 맙소사! 좀더 어려운 문제에 접근해보자. 당신은 모든 사람이 가톨릭 신자 혹은 힌두교 신자로 되어있는 나라에 살고 있다 가정해보자. 이미 사람들을 로마인들의 악랄한 손아귀(가톨릭)으로부터 때어내는 것 만으로도 힘들지 않은가? 그렇다면 반대로 사람들을 칼리, 크리슈나, 가네샤 신들을 숭배하게 하는게 맞는걸까?

예를 들어, 마멧은 보수주의 작가 [토마스 소웰](https://en.wikipedia.org/wiki/Thomas_Sowell)을 지지하는데, 그에 의하면 "우리 현대 최고의 철학자"라며 소웰을 칭송하고 있다. 글쎄 나도 토마스 소웰을 좋아하긴 한다. 그의 작품은 확실히 가치가 없는 것은 아니다. 그리고 구글에 검색하면 그의 칼럼이 [townhall.com](http://townhall.com/)이라는 보수주의적인 웹사이트에 자주 뜨는 것을 볼 수 있을 것이다.

위 예시의 링크를 클릭해보면 *극악한* 그래픽 디자인을 볼 수 있을 것이다. (오바마 캠페인 그래픽 디자인과 비교해놓고 봤을때 오바마쪽이 얼마나 앞선 디자인인지 차이가 느껴지시는가? 일부 폰트 디자이너들에 따르면 바로 [차이](https://archive.is/KSPs8)가 느껴진다고 한다.) 거기에서 폭스뉴스를 연상시키는 참혹함을 체험해보자. 그다음엔... 뭐, "뒤로가기"를 누르던지 아니면 덤으로 앤 콜터 칼럼을 읽거나, 아님말고. 

난 진보주의자가 아니지만 그렇다고 보수주의자도 아니다. (궂이 따지자면 난 [자코바이트](https://en.wikipedia.org/wiki/Jacobitism)다.) 오랜시간을 통해 나는 미국 보수주의 사상이 어떻게 돌아가는지 알게되었다. 일반적으로 폭스뉴스나 townhall.com에서 잘 팔리는 얘기들이 바로 그런 것이다. 일종의 호불호가 갈리는 취향이랄까? 이건 아마 버락 오바마가 제레미아 라이트 목사의 설교 스캔들을 다루는 방식과 매우 비슷하다고 볼 수 있다.  데이비드 마멧이 독자들에게 townhall.com을 설명하기 위한 방식은, 마치 동성애자에 대해 꺼림직해하는 삼촌에게, 게이는 딱히 나쁘지 않다는 설득을 위해 [살로소돔의 120일](https://www.imdb.com/title/tt0073650/)을 틀어주는 것과 같은 짓이다. 이건 소통이라기보단 "엿먹어라"에 가까운 짓이다.    

그런데 많은 이들은 자신이 진보가 될 수 없다면 보수주의자가 될 수 밖에 없다고 생각한다. 내가 예측하기로는, 많은 부류의 진보들이 갖는 감정적 동기로서 그들이 진보인 이유는 보수주의는 답이없고, 보수주의에 대해 근본적으로 무언가 뜯어 고쳐져야된다 생각되기 때문일 것이다. 게임오버, 또다시 제자리로.

NPR은 틀렸고 폭스뉴스가 옳다는 생각은 어디서 나온 것일까? NPR과 폭스뉴스는 서로 모순되는 말을 하기때문에 둘 다 옳을 수는 없는 노릇이다. 하지만 혹시 둘다 틀린 것은 아닐까? 나는 거기에서 나오는 정보들이 약간  틀렸다거나, 각각 반은 옳고 반은 틀렸다는 걸 말하려는 것도 아니며, 진실은 그들 사이에 있다는 것을 말하는 것도 아니다. 내가 말하고자 하는 바는  그것들 둘 다 현실과는 일관되지 않은 내용들을 담고 있다는 것이다.

이 점에 대해서는 잠시 생각해 보자. 진보주의자로서, 당신은 보수가 집단적 망상이라고 믿을 수 밖에 없다. 얼마나 기상천외한 일인가! 수많은 사람들중 에 대부분 둔하지만 꽤 똑똑한 사람들 조차도 그러한 망상속에서 살아간다. 우리는 이것을 당연하게 여긴다. 또한 우리는 이런 세태에 익숙해져있다. 하지만 곰곰히 생각해보면 이건 정말 이상한 일로 느껴질 수밖에 없다.

우리가 믿어야 할 것은 보수들은 그들 집단적으로 정보를 잘못 받아들여 오해를 하고 있다는 것이다. 그들은 바보가 아니다. 적어도 그들 모두가 바보는 아니다. 또한 그들이 악한 것도 아니다. townhall.com에서 시간을 보내다 보면 골룸 같은 놈들이 세계를 파괴시키고 노예화하려는 사악한 계획 따위는 찾아볼 수 없을 것이다. 그들은 당신과 같이, 보수주의자가 됨으로서 선과 진실을 위해 싸우고 있다고 생각하고 있는 것일 뿐이다.   


보수주의는 정부에 대한 개인적 경험이 없는 다수의 사람들이 갖고 있는 정부론이다. 그들은 주로 폭스 뉴스, townhall.com,  지역교회에서 나오는 선택적인 정보들을 통해 그들만의 정리된 이야기를 지지하고, 강화시키고, 확증에 들게한다.


그렇다면 왜 이런 이상한 패턴들이 존재하는 것일까? 왜냐하면 보수주의라 함은 일반적인 의견이 아니기때문이다. 정부론에 대한 논의 대신 보수를 농구와의 비유로 생각해보자. "보수주의"는 농구 선수와 코치들에게 중요한 픽앤롤 전법, 외곽운용, 삼각수비 그리고 다른 이슈들에 대한 관점의 체계일 것이다.

분명한 차이점은, 당신이 농구 코치가 아니라면, 농구 문제에 대한 당신의 의견은 전혀 반영되지 않을 것이다. 농구는 민주주의가 아니기 때문이다. 선수들은 팬들은 고사하고 투표조차 받지않는다. 그러나 보수주의는 일종의 '조직적인 망상'을 유지할 수 있는데, 왜냐하면 보수주의의 팬들은 단순한 팬이 아니기 때문이다: 그들은 정치 기계의 지지자들이다. 이 기계는 자신의 지지자들을 지키지 못하면 없어질 것이므로 지지자들을 지킬 동기가 생긴다. 그리고 그것은 정말로 그렇게 작동한다. 그게 어떻게 작동하는지도 보면 웃길따름이다.

자, 진보주의자로서 당신이 보는 미국의 민주주의는 이렇다-진실과 이성이 프로파간다, 무지, 거짓정보 위에 세워진 준범죄적 정치 기계와 대결하는 경합이다. 아마 세상을 냉소적으로 보는 시각일 텐데 진보주의가 옳다고 믿는다면 보수가 잘못됐다고 믿을 수밖에 없고, 다른 선택의 여지가 없을 것이다.

그러나 여기 더 비관적인 견해가 있다. 미국의 민주주의가 진리와 이성의 경합이 아니라 두 개의 준범죄적 정치 기계 사이의 경합이라고 가정해 보자. 진보주의도 보수주의와 똑같다고 볼 수 있을까? 만약 그렇다면, 누가 당신에게 그런 점을 알려주겠는가?

보수주의를 일종의 정신질환으로 생각해보자. 모기가 말라리아를 옮기는 수준의 전염성을 가진 폭스뉴스를 통한 바이러스 X가 미국인구 절반의 뇌를 잠식시켜 조지부시는 사실 '정상인'이고 지구온난화는 일어나지 않으며, 미군이야말로 사드르 시티에 진정한 민주주의를 가져올 수 있다고 믿게 만들었다. 다행이도 나머지 미국의 절반인구는 진보주의라는 항체로 보호되고 있는데, 이 항체는 매일 타임즈와 NPR이 제공하는 젖과 꿀물을 마시며 진실의 빛을 비출 수 있게 해준다.

그런데 그게 실제로 그런가? 방금 우리는 두 종류의 실체를 가정해 보았다. 바이러스와 항체, 모기, 그리고 젖과 꿀물. [오컴의 윌리엄](https://en.wikipedia.org/wiki/Occam%27s_Razor)은 방금의 가정에 행복해하지 않을 것이다. 대신에 우리가 바이러스 Y를 다루고 있다고 상상하는 것이 더 간단하지 않은가? 한 세트의 사람들이 감염되고 다른 한 세트는 면역이되는 것이 아니라, 모든 사람들이 감염된다. 단지 다른 변종들로 이루어지는 것일 뿐이다.

바이러스 X를 바이러스로 만드는 것은, 영화 죠스에 나오는 상어처럼, 이것들의 인생 유일한 목표는 먹고, 헤엄치고, 아기 바이러스를 만드는 것뿐이다. 즉, 그 특징은 여러상황에 따라 설명될 수 있다. 이게 만일 정확한 대변을 통해 실현 될 수 있다면, 현실에 반영이 될 것이다. 예를 들어 당신과 나 그리고 바이러스 X는 국제 유대인 음모설따위는 존재하지 않는다고 동의한다.우리는 다행히도 요즘은 보기 힘든  사악한 바이러스 N에 동의하지 않는다. 다른방식으로 말해보자면, 폭스 뉴스가 하켄크로이츠를 로고로 내세우고 빌 오라일리에게 시온 의정서에 대해 독설을 날리라고 한다면, 시청률은 아마 떨어질 것이다.

'현실과 일관된 관계가 없다'는 말은 이렇다. 어떤 이유에서든 간에, 진실보다 보수적 정신 안에서 오류를 재현하는 것이 더 낫다면, 보수주의자들은 그 오류를 믿게 될 것이다. 진리가 좀 더 순응적이면 그들은 진리를 믿게 될 것이다. 어떻게 오류가 진실보다 더 나은 이야기를 만들 수 있는지 폭스뉴스에서 보는 것은 꽤 쉽다. 따라서 그 근원에서 진실을 얻는거 당연히도 어려울 것이다.

정리하자면 의심을 향한 첫단계는 쉽다. 단지 진보주의자들이 신뢰하는 기관들 또한 같은 방식으로 잘못될 수 있다는 것을 스스로에게 의심을 하면 될 것이다. 만약 NPR이 폭스뉴스와 마찬가지로 오류를 재현할 수 있다면, 우리는 실제로 Y 바이러스를 보고 있는 것이다. 바이러스 X가 틀렸을 때 바이러스 Y가 옳을 수도 있고, 바이러스 X가 옳을 때 옳을 수도 있고, 바이러스 X가 틀렸을 때 틀린 것일 수도 있다. 이 둘이 현실과 일관된 관계가 없는 이상 이 둘 서로 또한 일관된 관계가 없다.

이 이론에는 흥미로울만한 대칭성이 존재한다. 그것은 바로 (세계와 역사의 기준에 의해) 어느 사회의 한쪽이 그다지 달라보이지 않는 다른 사회의 한쪽과 대칭을 이루어 비교적 정상적으로 보이게 한다는 것이다. 하지만 실제는 전혀 그렇지 않다.

게다가 이점은 아까 얘기했던 기괴한 모순이 담긴 마멧의 이야기와 맞아떨어진다. 거기에다 이제 마멧은, 그의 새로운 보수적인 견해를 다음과 같이 전하고 있다.

>정부의 역할은 무엇인가? 일반적으로, 내 왕년에는 정부가 좋은 것이라 생각했지만, 여태까지 내가 경험하고 지켜본바에 따르면, 정부의 개입은 슬픔보다 더한 고통을 남겨주었다.

하지만 아까 그는 우리에게 다음과 같이 말했다.

>60년대의 어린 시절, 나는 정부가 부패하고, 정부의 사업이 착취적이며, 선천적으로 사람들은 마음씨가 좋다는 것을 진리로 받아들였다.

60년대의 어린시절, 나는 정부가 나쁘다는 것을 진리로 받아들였지만...지금은 정부가... 나쁘다? 지금 누가 누구한테 [사도 바울의 회심](https://en.wikipedia.org/wiki/Conversion_of_Paul_the_Apostle)에  [급커브](https://en.wikipedia.org/wiki/Doughnut_(driving))를 돌리는 꼴인가?  

오늘날 미국 정치의 매혹적인 사실 중 하나는 진보와 보수 모두 정부를 싫어한다는 것이다. 그들은 단지 정부의 각기다른 부분들을 싫어하고, 그외 부분들은 사랑하고 소중히 여긴다. 예를 들어 외교정책에서는 진보주의자들이 국방부를 싫어하고, 국무부를 사랑하고 아낀다. 보수주의자들은 국무부를 싫어하고, 국방부를 사랑하고 소중히 여긴다.

이것이 우리의 바이러스 X-Y 이론과 얼마나 잘 들어맞는지를 보라. 워싱턴 주변에는 많은 지대들이 있는데, 그 중 일부는 바이러스 X 기계의 일부이고, 다른 일부는 바이러스 Y에 의해 영구히 감염되어 있다. 벨트웨이 지역 밖에는 바이러스에 감염되어 침을 흘리는 좀비 유권자들의 무리가 있다. X 좀비들은 Y 기관을 싫어하고, Y 좀비들은 X 기관을 싫어한다.

그러나 그들 중 누구도 워싱턴 전체를 싫어하지는 않는다. 그래서 그들은 결코 연합하여 그들의 정치기계 자체를 파괴할 수 없으며, 그 기계체제 전체는 안정화되어 있다. 이게 얼마나 아름다운지 보이는가? 유권자들을 경쟁적이지만 협력적인 두 정당으로 분리시킴으로써, 둘 중 어느 쪽도 상대방을 파괴할 수 없는 양당 체제는 그 시스템이 사라진다면 국민들의 삶이 얼마나 더 행복해질지는 상관하지 않은 채 무한히 살아남을 수 있는 정부를 만들어낸다.

이것이 우리가 마주한 의문의 진면목이다. 만일 당신이 보수주의자가 되지않되 진보가 되지않는 방법을 안다면, 당신은 정말로 정부에 대항하는 방법을 알아낼 것이다. 적어도, 당신은 이 양당체제 안의  정치인들, 사회운동, 기관들 중 그 어느 것도 여러분의 지지를 받을 만한 가치가 없다고 결정할 수 있을 것이다. 나를 믿는가? 이 깨달음은 당신을 해방시켜주는 경험이 될 것이다.
     

하지만 아직 우리는 이 단계에 오르지 못했다. 우리는 실질적으로 진보주의를 의심해야할 만한 진정한 이유를 찾지 못했다. 타임즈가 무슨 팩트체크 실수를 했네(아니면 뭐든간에) 따위의 사소한 오류들은 지금 우리가 이야기하는 이유가 되지 않는다. 이건 진보가 옳고 보수는 기본적으로 잘못되었다는 당신의 신념과는 아예 상관없는 부분이다. 약간의 편향적 시선으로 본다 하더라도 진보주의가 보수주의의 치료제라는 발상은 그대로 고수할만 하다. 바이러스 Y가 '항체'인지는 모르겠지만 적어도 백신 격으로 보아도 문제는 없을 것이다.           

게다가 우리는 진보와 보수가 내거는 사회운동 사이의 몇 가지 주요한 비대칭성을 간과해왔다.그들은 서로 못되먹은 쌍둥이 같은 관계가 아니다.그 둘은 매우 다른 것이다. 하나는 신용할 수 있고 다른 하나는 믿을만 하지  않을 것이라는 것이라는 이미지 속에, 그 이점들은 모두 진보쪽에 있는 것처럼 보인다.

먼저 _진보진영_ 인사들부터 살펴보자. "블루 스테이트(민주당 텃밭)" 와 "레드 스테이트(공화당 텃밭)"이라는 말이 있듯이, 오늘날 미국의 진보와 보수는 서로 다른 부류들이다. 이들은 아무 의견이나 가지고 있는게 아니다. 이들은 특정한 행동패턴을 가지고 있다.   

나와 내 아내는 몇주전 딸을 가지게 되었는데, 아내가 퇴원하기 직전 의사들은 우리아이가 경미한 수준의 (그리고 그리 해가 되진않을) 심장질환을 가지고 있는 것을 발견해, UCSF의 소아 심장학과장을 집으로 외진을 오게 한적 이 있었다. 그 소아과장 의사는 아주 유쾌한 사람이었는데, 그가 환자의 긴장을 풀게하기 위한 접근방식으로 우리에게 처음으로 말을 건 주제는 조지 W. 부시에 대한 얘기였다. 아마 그 의사가 우리를 스톡턴에서 온 촌놈으로 진단했다면 그가 이렇게 왁자지껄하지는 않았을 것이다.      

오히려 이 선량한 의사는 우리를 ['백인들이나 좋아할 것들'](https://stuffwhitepeoplelike.wordpress.com/)류의 부류로 보았다.[^1] 이 풍자용 사이트는 대략 UR이 가지는 10분의 1도 안되는 시간에 100배의 트래픽을 끌어 모았다. 이런 열광적인 관심은 뭔가 끌리는게 있다는 신호일 것이다. 이 사이트의 글쓴이인 크리스 랜더는 딱 한 가지 농담만 고수하고 있다. 그는 자기네들 스스로 묘사되길 싫어하는 자들을 그런 자들이 가질만한 전형적인 이름들과 하는 짓을 함께 묘사했다. 

[버닝 맨](https://journal.burningman.org/2012/01/philosophical-center/tenprinciples/is-burning-man-a-white-people-thing/)을 다녀온 사람이라면 누구나 알 수 있듯이 랜더가 말하는 '백인들'은 실로 백인스럽다. 그러나 동양인, 심지어는 흑인이나 라틴계중에 '백인'스러운 사람들은 얼마든지 있다. 사실, [랜더가 지적하듯이](https://stuffwhitepeoplelike.wordpress.com/2008/01/21/14-having-black-friends/), '백인들'은 인종 차별주의자와 정반대이다. 그들은 자기주변에 소수민족을 두고 싶어해 안달이다. 그에따라 이런 그들을 '백인'이라고 부르는 유머가 생겨났다. 사실, 일반 고등학교에 다닌 사람이라면 누구나 말할 수 있듯이, 랜더가 "백인"이라는 단어를 사용한 것은 거의 미국 흑인들이 쓰는 용어인 "그거 너무 백인스럽다"와 동일하다. 거기에다 흰둥이빵(Whitebread)이라는 속어를 얹어 생각해보면 이해가 될 것이다.

이런 이상한 작자들은 누구일까? 간략히 보자면, 이들은 미국의 지배계급이다. 여기 UR에서는 브라만이라고 부른다. 브라만 일족은 세습이라기보다는 계급으로 구성되어 있다. 누구나 브라만이 될 수 있고, 사실 자신의 배경이 덜 "백인"수록 더 좋다. 왜냐하면 그것은 자신의 업적이 자수성가 한 것이란걸 의미하기 때문이다. 힌두교의 실제사상과 마찬가지로 브라만으로서의 지위는 돈의 기능이 아니라 학자, 과학자, 예술가, 혹은 공인으로서의 성공에 대한 것이다. 브라만은 정신으로 일하는 사람들이다.

브라만은 말 그대로 통치하는 민족이기 때문에 지배계급이다. 현대 민주주의 체제에서 공공 정책은 주로 "백인"들이 모이는 [NGO](https://stuffwhitepeoplelike.wordpress.com/2008/01/21/12-non-profit-organizations/)에서 브라만에 의해 공식화된다. 그리고 모든 진보주의자가 브라만은 아니고 모든 브라만이 진보주의자는 아니지만, 일반적으로 진보들은 브라만적 행태를 따른다.

가장 중요한 것은 브라만의 정체성이 미국 대학 시스템과 불가분의 관계에 있다는 점이다. 만약 당신이 브라만 계급이라면 책 한권을 쓰거나, 환경보호일을 하는 것마냥 당신의 지위는 학문적 성공 혹은 어떤 유사학문적 성취에 의해서 정해진다. 그러므로 대부분의 브라만들이 상당히 지적이고 세련되었다는 것은 놀랄 일이 아니다. 그들은 그래야만 한다. 적어도 그들이  그렇게 꾸며내지도 못한다면 브라만이 아니다.

브라만의 천적은 물론 레드 스테이트 쪽의 미국인들이다. 나는 이 계급에 다른 힌두 카스트 이름인 _바이샤_ 로 부르려고 했는데, _마을지기_ 라는 이름이 더 부르기에 어울리는 것 같다.[^2] 진보주의자로서 당신은 아마도 브라만일 것이다. 당신은 아마 그런 마을지기 부류들의 사람들을 알고 있을 테고, 그런이들을 좋아하지 않을 것이다. 뚱뚱하고, 오로지 백인들뿐이고, 교외에 살거나, 참나무와 크로셰와 미니밴에 빠져있으며, 무엇보다도 공화당 성향이다. 그들이 아마 대학에 갔다면 신입생 민족다양성 교육에 이를 갈며 증오했을 것이다. 그들이 종사하는 일에 화이트 컬러 직종도 있겠지만 별로 지적인 일을 하지는 않는다.   


(흥미롭게도 이런 집단에 따른 분류는 미국정치가 얼마나 단순해지는지 보여준다. 이런 경우는 종종 제 3세계 국가들에게서도 찾아볼 수 있다. 말하자면, 앙골라 인민해방운동(Angolan People’s Movement)와 앙골라 민족해방전선(Democratic Angolan Front)가 예가 되겠다. 이 둘은 각자 스스로 앙골라 전체 국민의 미래를 위해 일한다고 맹세할 것이다. 하지만 여기서 앙골라 인민해방운동의 모든 사람들은 오밤보족이고, 앙골라 민족해방전선의 모든 사람들은 바콩고족이라는 것을 상기해보자.)

브라만과 마을지기의 지위 관계는 명확하다: 브라만은 더 위의 계급이고, 마을지기는 더 낮은 계급이다. 브라만이 마을지기들을 싫어할 때의 그 태도는 경멸이다. 마을지기들이 브라만을 미워할 때의 그 태도는 원한이다. 이 둘의  습성은 상이하다. 브라만과 마을지기들이 서로 [계층언어](https://en.wikipedia.org/wiki/Post-creole_speech_continuum)를 쓴다 가정한다면, 브라만족은 상류층 언어(acrolect)를 쓰는 쪽이고 마을지기들은 중산층 언어(mesolect)를 쓰는 쪽이다.

즉, 브라만은 마을지기들보다 _세련_ 되어있다. 기본적으로 더 좋은 취향을 가진  브라만들의 취향은 그 하위인 마을지기들을 향해 영향을 준다 . 20년 전만 해도 '건강식품'은 브라만들만 아는 서브컬처였다. 하지만 이제 건강식품은 사방지천에 널려 있다. 이젠 교외 거주민들도 에스프레소를 마시고, Whole Foods에서 쇼핑하고, 얼터너티브 록을 듣고, 여러가지 문화를 즐긴다.

따라서 우리는 왜 진보주의가 보수주의보다 더 세련되어있는지 그 이유를 알고 있다. 예를 들어 진보적인 유명인사들은 어디에나 있다. 보수적인 유명인사는 찾기가 드물다. 비록 많은 진보적인 유명인사들이 그들의 신념에 성실한 것처럼 보이지만, 그들은 대단히 냉정하고 계산적이다. U2의 [보노](https://en.wikipedia.org/wiki/Bono) 홍보 담당자들은 그가 [에이즈에 대해 목소리를 높인 것](https://en.wikipedia.org/wiki/Bono#Philanthropic_work)에 기뻐하고 있다. [멜 깁슨](https://en.wikipedia.org/wiki/Mel_Gibson)의 홍보 담당자들은 그가 [유대인들에게 목소리를 높인 것](https://en.wikipedia.org/wiki/Mel_Gibson#Alcohol_abuse_and_legal_issues)에 대해 기뻐하지 않는다.

그래서 보수주의에 대해 의문을 품을때 우리는 우리편을 위해 지극히 자연스럽게도 우리의 적들을 공격한다 . 그리고 그 적들은 실로 만만한 상대다. 사실 그 적들은 의심스러울 정도로 쉽게 밀려 넘어진다.

보수들 전체의 행동양식을 보자. 그들의 반경 모든것에서 악취가 풍긴다. 바이러스 X는 교육을 받지 못한, 일반적으로 지능이 떨어지는 사람들의 마음속에서 번식한다. 사실 마을지기들은 히틀러와 무솔리니를 배출한 이들과 똑같은 족속들이다. 그들로부터 나오는 신문찌라시, TV 채널, 별의별  싱크탱크들과 같은 지식 기관들은 비주류스러운 재벌들에 의해 지원된다. 정부내각에서 애국보수들의 최후의 보루는 인명을 살상하는게 목적이고 로비스트들에게 돈벌이수단이 되는(보통 환경을 파괴하는) 군부이다.

반면에, 바이러스 Y는 "바이러스"라는 말 그대로, 미국에서 가장 저명한 인재들로서, 일류 대학들, 위대한 신문사들, 록펠러, 카네기, 포드와 같은 오래된 재단들 전역 곳곳에 퍼져있다. 바이러스 Y에 걸린 우리들의 "침 흘리는 좀비들"은 사실 이 나라에서, 어쩌면 세계에서 가장 똑똑하고 성공한 사람들이다. 정부하에 바이러스 Y는 환경을 보호하고 빈자들을 돌보고 아이들을 교육함으로서 세계의 평화를 건설한다.

실상은 진보주의야말로 미국의 주류 전통이라는 것이다. 이것이 그렇다고 우리의 관습이 지난 200년 동안, 심지어 지난 50년 동안 변하지 않았다는 것을 의미하지는 않는다. 

그러나 주류 하버드에서 배우고 가르치는 국가역사의 사상과 이상을 살펴보면 지금까지 우리는 대단히 순조로운 진보만을 봐오고 있다. 우리는 격렬한 역사적 역행이나 심지어는 변곡점마저도 보지 못했으며, 결국 오래된 근대적 진보주의로 끝을 맺게 되었다. 물론 여기서, "미국의 전통"은 뉴잉글랜드의 전통을 의미한다. 만일 남북전쟁이 다르게 전개되었다면, 상황은 다르게 흘러갔을 수도 있었을 것이다. 그러나 [150년 전](https://en.wikipedia.org/wiki/The_Blithedale_Romance)에 내새니얼 호손(Nathaniel Hawthorne)이 히피 공동체에 관한 소설을 썼다는 것을 알고있다면, 태양 아래서는 새로운 것이 없다는 것을 깨닫게 될 것이다.

마키아벨리가 말했듯이, 왕을 치려거든 죽이기 위해 쳐라.[^3] 수많은 난잡한 배경과 겨우 50년 밖에 안된 보수주의는 조롱과 경시, 경멸을 받을만 하다. 보수에 대한 비판과 진보에 대한 비판의 차이는 몰몬교 비판과 기독교 비판과 같다. 진보주의는 조금씩 의심할 것이 되지 못한다. 의심을 하려면 그 전체를 의심해야한다. 

보수주의가 부패하고 망상적인 전통이라거나, '바이러스 X'에 지나지 않는다고 하는 것은, 일탈, 낙태, 그리고 미국일면의 흔히 고쳐야 할 여러오류들이 티끌에 지나지 않는다고 하는 것과 같다. 교육의 실패, 리더십의 실패, 진보의 실패. 이들은 정말로 작은 것에 지나지 않는다.

진보주의를 의심하는 것은 미국의 근본적인 사상을 의심하는 것이다. 왜냐하면 진보주의는 그 자체로 종결이 난 것이기 때문이다. 진보주의가 '바이러스 Y'라고 친다면 미국 자체가 이미 그것에 감염된 것이나 마찬가지다. 그렇다면 이에 대한 치료법은 무엇일까? 그것은 바로 이상하고 끔찍한 발상으로 생각될, 즉 종말의 필연이다.

그럼에도 아직 이 결론은 끔찍한 해답으로 받아들여질 것이다 . 우선, 만약 당신이 정신바이러스의 입장에 놓여있다고 생각해 본다면, 어떤 전통을 선택해서 감염시키는게 좋겠는가? 현재 미국의 핵심사상, 아니면 다른  허술하고 미개한쪽? 브라만족, 아니면 마을지기족? 세련된 자들, 아니면 유행에 뒤떨어지는 자들?

당신의 DNA를 뉴욕 타임즈에 전이 시켜보자, 30년 내지 20년 안에 그 여파는 폭스 뉴스로 흘러가게 될 것이다. 그 여파가 폭스 뉴스로 흘러가게 되면 그 효과는 다음 선거에 영향을 미칠지도 모른다. 아니면 그 이후에도. 하지만 그게 얼마나 오래갈까? 조지 W 부시에게 지적으로 감동을 받는 사람이 얼마나 될까?(반발심으로 만들어진 관심들은 여기에 고려하지 않는다.)

브라만(나는 당신이 브라만이라고 가정할 것이다)으로서 당신은 바이러스 Y 속에 살고 있다. 당신은 그 좀비들 중에 한 명이다. 당신의 세계관은 하버드, 타임즈, 그리고 나머지 한때 기득권이라 불리던 데이비드 마멧 세대에 의해 만들어졌다. 정부, 역사, 과학, 사회에 대해 당신이 알고 있는 모든 것들은 이 기관들에 의해 걸러졌다. 분명히 방금의 서술은 모순되지 않는다. 하지만 과연 이게 사실일까?

자, 상기한 서술들은 모순되지 않는다. 아주 잘 짜여져있다. 하지만, 정말 자세히 돌이켜 본다면,  실낱같은 오류를 찾을 수 있을 것이다. [트루먼 쇼](https://en.wikipedia.org/wiki/Truman_Show)의 짐 캐리마냥 세상의 가장자리로 항해할 필요는 없다. 단지 우리에게 필요한건 의심이라는 근육을 자극시키기 위해 미세한 경련을 일으킬 몇가지 일치하지 않는 모순들이다.   

세 가지 질문으로 시작해보자. 일종의 간단한 게임을 해보도록 할텐데, 내가 비진보주의적인 대답을 생각해내면 당신은 진보주의적인 대답을 생각해내보도록 하자, 어느 쪽이 더 말이 되는지 두고 보면서.

이런 질문들이 진보적인 해답이 없다는 뜻은 아니다. 모든 것에 보수적인 해답이 있듯이 진보적인 해답도 존재한다. 진보적인 방안을 모색하는 것이 부족하지는 않을 것이다. 하지만 본 질문들에 대해 만족스러운 진보적인 해답이 나올 것이라 생각되지는 않는다. 물론 이는 당신 스스로의 좋은 직관을 가지고 판단해야 할 것이다.

첫째: 제3세계는 어떻게 되었는가?

예를 들어, 여기 말라리아와의 싸움에 다룬 [타임즈 기사](https://archive.is/CKxNM)를 보자. 종종 정치인들과 마찬가지로, 기자들은 그들의 진짜 관심사가 다른 것일 때, 공허한 상태의 진실을 말한다. 방금의 기사를 읽어보면, 다음과 같이 믿기힘든 내용으로 끝나는 문단을 볼 수있을 것이다.

>그리고 세상은 바뀌었다. 1960년대 이전에, 식민지 정부와 기업들은 말라리아에 맞서 싸웠다. 왜냐하면 그곳의 관리들은 나이지리아의 언덕 마을이나 베트남의 산간지역과 같은 외진 전초기지에 살았기 때문이다. 독립 운동은 자유로 이어졌지만 내전, 빈곤, 부패한 정부, 의료 붕괴로 이어지는 경우도 많았다.

그 마지막 문장에 초점을 맞춰보자. *독립 운동은 자유로 이어졌지만 내전, 빈곤, 부패한 정부, 의료 붕괴로 이어지는 경우도 많았다.*

나는 이러한 문제들이 주어질때 내가 목성에서 온 외계인이라 생각하고 접근하는 방식을 좋아한다. 이 문장에서, 나는 이렇게 묻고 싶다: 이 자유란 단어는 무엇인가? 여기서 글쓴이가 말하는 자유란, 정확히 어떤 것인가? 특히 내전, 빈곤, 부패한 정부라는 맥락에서?

여기서 우리가 보는 것은, 이 자유라는 기이한 추상적 개념과 더불어 글쓴이가 분명히 좋은 것이라 믿고 있던 독립 운동이, 매우 구체적이고 매우 끔찍한 결과를 초래했다는 것이다. 분명히 이 특정한 맥락에서 자유가 무엇을 의미하든지 간에 그 결과는 긍적적인 의미로서 *내전, 가난, 부패한 정부, 의료 붕괴*를 보태도 여전히 득을 보는 것으로 받아들여진다.

이상하지 않은가? 이 특별한 계산법에 대해 재고해보고 싶지 않은가? 하지만 우리는 그럴 수 없다. 만약 우리가 자유가 없는 식민지 정부와 기업(무엇이든 간에)이 위에 서술된 자유를 만들어내는 독립 운동보다 더 바람직했다고 가정한다면, 우리는 진보적 입장에서 벗어날 수밖에 없다.

사실 이 발상은 진보적 입장에서 벗어나 있을 뿐만 아니라 보수적 입장에서도 벗어나있다. 아무도 이것을 믿지 않는다. 폭스 뉴스나 townhall.com이나, 가장 형편없는 찌라시들 조차도 본질적으로 자유가 없는  식민주의와 이상하게도 효과적인 말라리아 통제가
(위의 예로나온 말라리아 기사에서도, 직접적인 언급없이도, 말라리아 구제는 단지  악랄한 식민지 군주의 이기적인 목적을 위해 행해졌을 뿐이라는 맥락의 암시를 주목해보자), 자유, 말라리아, 내전 등을 동반하는 탈식민지주의(postcolonialism) 보다 우월하다고 하지는 않는다. 

그리고 이 *독립*이라는 단어는 무슨 말인가? *자유*와 같은 의미인 것 같기도 한데, 그럼에도 기이한 개념이다. 예시로 [CFR](https://www.cfr.org/)의 미셸 게빈이 쓴 [기고문](https://archive.is/ipDSI)에선 다음과 같은 흥미로운 구절로 시작되는 것을 볼 수 있다:

>1980년 독립국이 되었을 때의 짐바브웨는 국제적 낙관론을 향한 아프리카의 미래의 단초였다. 오늘날의 짐바브웨는 무능한 나라이다.

목성에서 떨어진 외계인의 관점을 다시 써보고, 다음과 같은 구절을 생각해 보자: *1980년 독립국이 되었을 때의 짐바브웨는...*

보통 우리가 말하는 영어에서, *독립적*(independent)라는 단어는 부정형을 뜻하는 접두사 *in*과 의존적임을 뜻하는 *dependent*와 합쳐진 말이다. 그렇기에 예를들어 미합중국이 *독립*(in+dependent) 되었다는 말은 다른 외부적인 세력이 정부를 지원하거나 지배하지 않고 있었다는 것을 의미한다. 만약 내 딸이 *독립적*이게 된다면 그건 그녀가 이 세상에서 스스로 결정을 내리고 있다는 것을 의미할 것이고, 나는 내딸인 그녀에게 3시간마다 젖병을 물릴 필요도 없을 것이다. 


그러나 짐바브웨 사례의 경우를 보면, 이 말이 이상하게 바뀌어 거의 정반대의 의미를 띠게 된다. [위키](https://en.wikipedia.org/wiki/Unilateral_Declaration_of_Independence_%28Rhodesia%29)에 따르면:

>영국으로부터 로디지아의 일방적 독립 선언(The Unilateral Declaration of Independence)은 1965년 11월 11일 당시 영국 식민지에서 흑인들의 다수결 원칙에 반대한 로디지아 국민전선당(Rhodesian Front party)의 이언 스미스 행정부에 의해 서명되었다. 해당조항에 의하면 로디지아는 영국으로부터의 독립을 선언했지만 엘리자베스 2세 여왕에 대한 충성을 유지했다. 영국 정부와 영연방당국, 유엔은 해당 조항이 불법이라 규탄하였다. 로디지아는 1980년 짐바브웨로 독립하기 이전까지, 1979년부터 1980년까지의 짧은 기간 동안에 "영국령 남로디지아"로 영국으로부터 실질적인 지배를 당했다.

그리하여 이상하게도, 오늘날 짐바브웨로 알려진 이 나라는 미국이 1776년에 _독립_ 을 선언했었듯이 1965년에 _독립_ 을 선언했다. 그러나 전자는 _진정한_ 독립이 아니라 오히려 _불법적인_ 독립이었다. 진정한 _합법적_  독립을 얻기 위해, 짐바브웨로 알려진 이 나라는 우선 영국의 지배로 되돌아가야 했고, 즉 _불법적인_  독립을 포기해야 했다. 아직 혼란스러운가? 여기를 좀더 파고들어 보자:

>1980년 독립국이 되었을 때의 짐바브웨는 국제적 낙관론을 향한 아프리카의 미래의 단초였다. 오늘날의 짐바브웨는 무능한 나라이다. 지난 10년 동안 로버트 무가베 대통령과 집권당은 자신들의 권력에 대한 도전을 용납하지 않는 행태는 짐바브웨 핵심 경제체계 및 정치체제를 조직적으로 해체하고 그 빈자리는 부패, 뇌물, 탄압으로 대체하게 되었다.

그리하여 새로운 _자유_  짐바브웨의 _독립적_ 지도자들은 _그들의 권위에 도전하는 것을 용납하지 않았다._ 따라서 1980년엔 젖병이 필요해 어렸을 게빈과 그녀의 동종업계의 사람들이 지지해온 _국제적 낙관론_ 은 비관주의와 무능함으로 전락해버렸다. 여기서 과연 누가 무가베 대통령의 권력에 도전했을까? 아마도 _짐바브웨 핵심 경제체계 및 정치체제를_  해체할 의도가 없는, 게빈과 권위와 영향력을 가진 그녀의 업계사람들로부터 신뢰를 얻을 만한 자들이었을 것이다. 여태까지 지켜본 바로는 이 _독립_ 이란 것은 실로 기이한 개념이다. 

자기 스스로 자급자족하고 자기를 먹일 '젖병'따윈 절대로 필요없는 의미에서 실제로 세계에서 가장 독립된 나라가 하나 있긴 하다. 그 나라는 바로 [소말릴란드](https://en.wikipedia.org/wiki/Somaliland)인데 , 국제사회에서 누구에게도 _인정_ 받지 못하고 있다. 소말릴란드의 수도인 [하르게이사](https://en.wikipedia.org/wiki/Hargeisa)의 위키피디아 페이지는 의도치 않은 코미디를 선사한다.

>외국 정부의 원조는 존재하지 않으며 아프리카에서는 대외원조에 대한 의존도가 낮은 이례적인 국가이다. 소말릴란드는 실질적으로 독립국가에 위치해있지만 국제적으로는 (법적으로) 독립국가의 지위를 인정받지 못하고 있다. 따라서 소말릴란드 정부는 IMF와 세계은행의 원조를 지원받을 수 없다.

이 모든 게 상당히 궁금하지 않은가? 짐 캐리가 요트를 세상의 경계가 그려진 외벽으로 들이받는 장면이 조금이라도 연상되지 않는가?

둘째: 내셔널리즘이란 무엇인가? 내셔널리즘은 좋은 것인가 아니면 나쁜 것인가?

이 질문은 첫번째 질문과 다소 유사하다. 나는 이에 대해 내가 존경하는 한 [진보 논객 블로거](https://nihoncassandra.blogspot.com/)가 "호치민은 내셔널리스트"라는 얼버무린 대답을 생각하곤 한다. "당연하지", 그에대해 나 스스로 되뇌인다.  "물론 팻 뷰케넌도 말이야".  방금 얘기한 것들은 앞으로 우리가 나갈 진도에 비해 성급한 내용이긴 하지만 피래미 같은 여러 첨언들을 더해보고 싶었다( _mot d’escalier_ ).


_독립_ 이라는 개념과 달리, [내셔널리즘](https://en.wikipedia.org/wiki/Nationalism)의 정의에 대해선 대부분 사람들의 이견은 없을거라 생각한다. 내셔널리즘(라틴어로 탄생을  뜻하는 _natus_ 에 유래됨)이란 공통의 언어성, 민족성, 혹은 인종성을 가진 사람들끼리 하나의 정치적 독립체를 갖는 것을 말한다. 독일식 내셔널리즘은 독일인이 가지는, 베트남식  내셔널리즘은 베트남인이 가지는, 흑인 내셔널리즘은 아프리카계 미국인이 가지는, 미국식 내셔널리즘은 팻 뷰캐넌이 가지는 내셔널리즘이다.

그리고 우리들의 합의된 이야기는 여기서 끝난다. 위키피디아 [도입부 설명](https://en.wikipedia.org/wiki/Nationalism)을 보면 가관이다:

>내셔널리즘이란 국민(nation)은 공통의 역사와 운명을 공유하는 독립적, 자주적 정치 공동체를 민족성이나 문화에 의해 구성할 권리가 있다고 하는 정치운동 혹은 신조이다.대부분의 내셔널리스트들은 국가의 경계와 국민의 경계가 일치해야 한다고 믿는다. 그러나 최근 내셔널리스트들은 그러한 호혜를 위한 '일치'를 거부해왔다. 현대의 내셔널리스트들은 국가가 단일 민족에 의해 통치되는 것이 아닌, 국민이 단일 국가에 의해 통치되어야 한다 주장한다. 때때로 내셔널리스트들의 노력은 쇼비니즘이나 제국주의에 의해 치러져 왔다. 이러한 이전의 내셔널리스트들의 노력들은 20세기 파시스트 운동에 의해 선동된 바가 있듯이, 내셔널리스트의 개념은 국적이야말로 개인의 정체성에 제일 중요하다 고수되고 있지만, 그들 내셔널리스트 중 일부는 인종이나 유전학적으로 부정확하게 국민(nation)을 정의하려 시도해왔다. 다행히도, 현대의 내셔널리스트들은 이들 집단의 인종적 우월주의를 거부하고, 민족 정체성이 민족에 대한 생물학적 애착을 대체한다고 자부하고 있다.
 

장담컨데, 이들 문장 하나하나가 순전히 헛소리이지만, 첫 문장과 마지막 문장의 직접적인 모순에 주목해보자. _민족 정체성이 민족에 대한 생물학적 애착을 대체한다_ 고 믿는다면 어떻게 _내셔널리스트_ 가, 아니면 심지어, _현대의 내셔널리스트_ 가 될 수 있을까? 내셔널리즘이 인종적 쇼비니즘에 의해 _치러지는게_ 아니라면 그게 어떤 의미에서 내셔널리즘이란 말인가?

내가 체코인이고 오스트리아-헝가리에 살고 있다면, 내 나라에 대해 권리가 있는 것인가? 그 권리를 받을때까지 폭탄 태러와 폭력을 행해야되는 것인가? 만일 내가 독일인이고 체코슬로바키아에 산다면 어떻게 할 것인가? 또 폭탄태러와 태러를 일으켜야 하나?

많은 독일인들이 1920년대와 1930년대에 이 이상한 점을 알아차렸다. 그들은 미국과 미국의 동맹들이 독일인의 경우를 제외한 민족자결에 대단히 헌신적이라는 것을 알아차렸다. 체코의 내셔널리즘은 좋다, 독일의 내셔널리즘은 나쁘다.

일단 캔버스에서 이 작은 실낱을 찾기 시작하면, 어디에서나 발견하게 될 것이다. 흑인 민족주의자(내셔널리스트)가 되는 것은 좋은 일이다, 아주 좋은 일이다. [제레미아 라이트 스캔들](https://en.wikipedia.org/wiki/Jeremiah_Wright_controversy)을 보면 우리는 진보주의와 흑인 민족주의 사이의 깊은 유대감이 형성되는걸 볼 수 있다. 이에 대한 건 [토머스 울프](https://en.wikipedia.org/wiki/Radical_Chic_&_Mau-Mauing_the_Flak_Catchers)가 어떤지 잘 보여 주었다. 실제로, 미국의 모든 유명한 대학에는 학생들이 전문적으로 흑인 민족주의를 전공할 수 있게 하는 [부서](https://aaas.fas.harvard.edu/)가 있다.

반면에 남부 내셔널리스트가 되는 것은 나쁘다, 매우 나쁘다. 남부 네셔널리즘과 어느방식으로나 연관이 있는 자는 즉각적으로 [파리아](https://en.wikipedia.org/wiki/Trent_Lott) (불가촉 천민)이 되어버린다. 물론 남부 네셔널리스트들은 [죄](https://en.wikipedia.org/wiki/Ku_klux_klan)를 지었다. 하지만 [흑인 민족주의자들](https://en.wikipedia.org/wiki/Zebra_murders) 역시 마찬가지다. 과연 미국인들은, 흑인이든 백인이든간에 흑표당, 네이션 오브 이슬람, 아니면 우리의 진실한 제레미아 라이트 목사의 활동을 위하는게 서로 좋은 것일까?

마찬가지로 베트남 내셔널리스트가 되는 것은 좋다. 독일 내셔널리스트나 영국 내셔널리스트, 아니면 프랑스 내셔널리스트가 되는건 여전히 나쁘지만 말이다. 독일인, 영국인, 프랑스인은 모든 인류의 공통된 운명공동체를 믿게 되어 있다. 베트남인 멕시코인, 혹은 체코인은 자유롭게 베트남, 멕시코, 체코의 운명공동체를 믿으면 된다.(사실 체코인에 대해서는 잘 모르겠다.)

이게 말이 되는가? 아니 _정말로_ 이게 말이 되는 소리인가?

이건 꽤 까다로운 주제이기 때문에, 미리 말하지만, 나는 어떤 종류의 네셔널리즘도 믿지 않는다. 물론, 나는 자코바이트고 또한 스트라포드의 [근본성(Thorough)](https://en.wikipedia.org/wiki/Thorough)을 믿는다, 따라서 당신은 나에게서 헌법적인 조언을 기대하긴 글렀다.

셋째: 나치가 뭐가 그리 나쁜가?

자, 그들은 천만명을 죽였다. 참 안타까운 일이다. 수백만 명의 민간인 학살을 옹호하는 것은 정말 있을 수 없는 일이다 .

한편, [니콜슨 베이커](https://en.wikipedia.org/wiki/Nicholson_Baker)의 신간 [인간 연기](https://www.amazon.com/Human-Smoke-Beginnings-World-Civilization/dp/1416567844)를 읽는걸 정말로 추천한다. 베이커는 진보주의자이자 흠없이 믿을만한 평화주의자이다(그의 이전 소설은 부시 대통령을 암살하는 환상을 가진 소설이었다). 그리고 _인간연기_ 가 주는 메시지는 다름이 아니라, 내가 계속 말하고자 하는 바와 일치한다: 일련의 이야기들이 서로 맞지 않는다. 서로 거의 맞지만  잘 안 맞는 이야기를 보여준다. 베이커가 보여주는 천재성은 바로 단순히 일련의 이야기들이 어울리지 않는 것을 보여주고, 분석은 독자에게 맡긴다는 것이다.

예를 들어, 우리는 나치들이 대량학살을 저질렀기 때문에, 더 정확히 말하자면 홀로코스트를 저질렀기 때문에 나쁘다고 배운다. 반면에... (a):
유대인들이나 홀로코스트에 대해 생각컨데, 그 어떤 연맹도 우리를 포함에  나치에 대항하지 않았다; (b): 우리 쪽 연맹 중 하나는 당시 대량 학살을 기록한 적어도 나치만큼 끔찍했던 소비에트 연방이었다.

그리고 물론 (c) : 연합군은 독일과 일본 민간인들을 대량으로 공중에서 태워죽이는 것을 긍정적으로 다뤘다. 6백만 명을 죽이지 않았지만  일이백만명 정도를 죽였다. 이런 부분에 대해서 군사적 측면에서 변명하는 부분이 있었지만 상당히 껄끄러운 부분이 있다. 그것은 (물론 적 민간인으로 본) 유대인들을 살해한 나치의 변명보다 나았다. 사실, 엄청 더 나은 변명이었다. 그런데 그게 엄청 엄청 더 나은 변명이었는가? 난 잘 모르겠다.

그리고 베이커가 언급하지 않은, 우리의 영웅인 연합군도 전쟁 후 [러시아 난민 백만 명](https://www.fff.org/explore-freedom/article/repatriation-dark-side-world-war-ii-part-3/)을 수용소로 추방하거나, 수십만 명의 독일군 포로들을 소련에 [노예강제징용](https://en.wikipedia.org/wiki/Forced_labor_of_Germans_in_the_Soviet_Union)으로 빌려주는 것에 대해 거리낌이 없었다. 제2차 세계대전을 인권을 위한 전쟁으로 보는 발상은 그야말로 반역사적이다. 이야기가 맞지 않는다. 나치의 인권침해가 지금 우리가 살고 있는 세상을 만든 전쟁의 동기가 아니었다면 그게 무엇이었을까?

더군다나 오늘날 미국의 외교정책을 당연히 비판하고 있는 베이커는 이라크와 독일에도 이와 똑같은 기준을 적용하려 할 때 나오는 당혹감을 보여준다.


만약 [아부그라이브](https://en.wikipedia.org/wiki/Abu_Ghraib_torture_and_prisoner_abuse)가 이라크에 민주주의를 강제하는데 그 간격을 매꿀 수 없는 장애물이라면, [드레스덴 폭격](https://en.wikipedia.org/wiki/Bombing_of_Dresden_in_World_War_II)과 [함부르크 폭격](https://en.wikipedia.org/wiki/Bombing_of_Hamburg_in_World_War_II), 그리고 독일에 대한 폭격은 어떻게 설명할 것인가? 확실히 수만 명을 산 채로 태우는 것이, 조악한 전선을 두르고 우스꽝스러운 모자를 쓰고 [상자 위에 서게 하는 것](https://commons.wikimedia.org/wiki/File:AbuGhraibAbuse-standing-on-box.jpg)보다 더 나쁘단 말인가? 아니면 이라크가 독일과 다를 뿐인건가? 근데 그건 인종차별아닌가?

파시스트 대량학살과 마르크스주의자들의 대량학살에 대한 반응을 두고볼때 이에 독특한 비대칭성이 나타난다. 두 이데올로기 모두 분명히 대량학살의 역사를 가지고 있다. 만약 수치가 중요하다면, 왜 그렇게 따지지 않을까?— 마르크스주의자들의 학살은 [규모 면](https://en.wikipedia.org/wiki/The_Black_Book_of_Communism)에서 앞서 있다. 그러나 어찌된 일인지 오늘날 파시즘이나 그것을 연상시키는 것은 건드릴 수 없는 순수한 악인 반면에 마르크스주의는 기껏해야 사소한 실수의 일종으로 보여진다. 존 즈미락은 여기에 대한 멋진 [패러디](https://www.takimag.com/article/saying_no_to_tenured_fascists/)를 보여준다. 또한 [로베르토 볼라뇨](https://en.wikipedia.org/wiki/Roberto_Bola%C3%B1o)를 읽고있는 중인데, 그 [리뷰들](https://archive.is/AEga)은 꽤 빛을 발한다.

소련도, 제3제국도 오늘날 우리와 함께 하진 않지않고 있다, 하지만 가장 최근의 역사적 예는 북한과 남아프리카이다. 아파르트헤이트인 남아프리카는 그 상황이 느슨해졌긴 했어도 여전히 나치즘과의 연관성을 알아볼 수 있는 곳이고, 북한은 분명히 어느 정도 스탈린주의적이다. 혹시 여기에 이민자들을 막기
위해 만들어진 국경장벽을 가지고 있는 남아프리카는 나라 자체가 감옥인 북한보다 더 나쁜 인권침해국이었다는 것을 주장하고 싶은 사람이 있다면 환영한다.  그리고 또 우리는 여기서 북한과는 ["소통"](https://en.wikipedia.org/wiki/2008_New_York_Philharmonic_visit_to_North_Korea), 남아프리카와는 적대라는 똑같은 비대칭성을 볼 수 있다 .  만약 당신이 뉴욕 필하모닉이 양국의 신뢰를 구축하기 위해 프리토리아를 방문하는 것을 상상할 수 있다면, 당신은 볼라뇨의 세상에 살고 있는 것과 마찬가지일 것이다.

다시 말하지만, 이건 정말 이상하다. 내셔널리즘과 마찬가지로 각각의 개별적인 사례도 그 나름의 용어로 설명될 수 있다. 모든 사건을 종합해 보면 이중잣대가 도처에 널려 있다. 그럼에도 불구하고 그 모순들은 무작위로 보이지 않는다. 거기엔 나치들은 가지고 있지만 소련은 가지고 있을 것 같지 않는, 남아프리카는 가지고 있지만 북한은 가지고 있을 것 같지 않는 X라는 요인이 존재하는 것 같다. 그에 취급은 단지 X뿐만이 아니라 X+인권의 개념일수도 있는데 이게 단지 인권을 위한게 아니란건 확실하다. 하지만 아직 우리는 X가 무엇인지 설명하지 않았다. 

X는 나치가 '우파'이고 소련이 '좌파'라는 것과 관련이 있는 듯하다. 옛말에 프랑스어로 말하길: pas d’ennemis à gauche, pas d’amis à droite.[^4]  그런데 왜일까? '우파'와 '좌파'는 무슨 의미까지 있는 것일까. 소련과 나치 체제 모두 전체주의 독재가 아니었던가? 공산주의가 '너무 뜨거운 것'이고, 파시즘이 '너무 차가운 것'이고, 자유민주주의가 '그저 옳다'면 왜 사람들은  공산주의와 파시즘을 동등하게 반대하지 않는 것일까? 사실, 전자는 적어도 1945년 이후엔 훨씬 더 성공적이었던 것이기 때문에, 당신은 사람들이 이에 대해 더 걱정하게 된 것이라 생각할 것이다.

다시 말하지만 우리는 순전히 혼란에 빠져 있다. 수평선이 캔버스로 이루어져 있다는 것은 도저히 있을 수 없는 일이다. 그럼에도 불구하고 우리들의 여정이라는 함선은 부딪혀, 큰 구멍의 자취를 남겼다.

[^1]:이말은 아예 "[SWPL](https://en.wikipedia.org/wiki/Stuff_White_People_Like)"(스위플로 발음)이라는 줄임말을 사용하는 것이 일반화되었다.
[^2]:Moldbug는 나중에 이 계급에 대해 더 나은 용어를 위해 _아메리카너_ 라는 단어를 창안했다. 남아프리카의 _아프리카너_(보어인)에 유추하여 만들어진 용어이다. 그가 쓴 "[외국의 영토를 점령하고 통치하는 방법](https://www.unqualified-reservations.org/2008/09/how-to-occupy-and-govern-foreign/)"에서 그는 다음과 같이 적고 있다. 


    >그들의 [어휘적 비유](https://en.wikipedia.org/wiki/Afrikaner)처럼, 아메리카너들은 유럽을 기반으로 한 문화집단이지만, 그들의 문화전통은 현대 의 유럽과는 유사성을 찾기가 힘들다.

[^3]: 이 방식의 정석은 [랠프 월도 에머슨](https://en.wikipedia.org/wiki/Ralph_Waldo_Emerson)에 의해 [정립되었으며](http://www.barrypopik.com/index.php/new_york_city/entry/if_youre_going_to_shoot_the_king_dont_miss), [올리버 웬델 홈즈](https://en.wikipedia.org/wiki/Oliver_Wendell_Holmes_Jr.)에 의해 대중화된 방식으로 자리잡았다. 이에 대해 영감을 준 [구절](https://simple.wikiquote.org/wiki/Niccol%C3%B2_Machiavelli#Sourced_quotes)은 마키아벨리의 [군주론](https://www.gutenberg.org/files/1232/1232-h/1232-h.htm)에서 찾아 볼 수 있다. 

    > 이와 더불어, 군주는 국민들을 아주 잘 대해주거나 아니면 철저히 잔혹하게 대해야한다는것을 명심해야 한다. 왜냐하면 국민들은 작은상처에 대해서는 복수 할 수 있지만, 심각한 상처에 대해서는 복수할 수 없기 때문이다. 이 때문에 한 사람에게 가해진 상처는 복수할 엄두가 나지 않을 정도가 되야한다.

[^4]: 보통 "좌(左)에는 적이 없고, 우(右)에는 친구가 없다"라고 알려져 있다.